/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicChangePasswordRouteImport } from './routes/_public/change-password'
import { Route as ProtectedTermsIndexRouteImport } from './routes/_protected/terms/index'
import { Route as ProtectedSupportIndexRouteImport } from './routes/_protected/support/index'
import { Route as ProtectedRbacIndexRouteImport } from './routes/_protected/rbac/index'
import { Route as ProtectedOrganizationsIndexRouteImport } from './routes/_protected/organizations/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedAuditIndexRouteImport } from './routes/_protected/audit/index'
import { Route as ProtectedAnnouncementsIndexRouteImport } from './routes/_protected/announcements/index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicChangePasswordRoute = PublicChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedTermsIndexRoute = ProtectedTermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSupportIndexRoute = ProtectedSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRbacIndexRoute = ProtectedRbacIndexRouteImport.update({
  id: '/rbac/',
  path: '/rbac/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrganizationsIndexRoute =
  ProtectedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAuditIndexRoute = ProtectedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAnnouncementsIndexRoute =
  ProtectedAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/change-password': typeof PublicChangePasswordRoute
  '/login': typeof PublicLoginRoute
  '/announcements/': typeof ProtectedAnnouncementsIndexRoute
  '/audit/': typeof ProtectedAuditIndexRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/organizations/': typeof ProtectedOrganizationsIndexRoute
  '/rbac/': typeof ProtectedRbacIndexRoute
  '/support/': typeof ProtectedSupportIndexRoute
  '/terms/': typeof ProtectedTermsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/change-password': typeof PublicChangePasswordRoute
  '/login': typeof PublicLoginRoute
  '/announcements': typeof ProtectedAnnouncementsIndexRoute
  '/audit': typeof ProtectedAuditIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/organizations': typeof ProtectedOrganizationsIndexRoute
  '/rbac': typeof ProtectedRbacIndexRoute
  '/support': typeof ProtectedSupportIndexRoute
  '/terms': typeof ProtectedTermsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/change-password': typeof PublicChangePasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/announcements/': typeof ProtectedAnnouncementsIndexRoute
  '/_protected/audit/': typeof ProtectedAuditIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/organizations/': typeof ProtectedOrganizationsIndexRoute
  '/_protected/rbac/': typeof ProtectedRbacIndexRoute
  '/_protected/support/': typeof ProtectedSupportIndexRoute
  '/_protected/terms/': typeof ProtectedTermsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/announcements/'
    | '/audit/'
    | '/dashboard/'
    | '/organizations/'
    | '/rbac/'
    | '/support/'
    | '/terms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/announcements'
    | '/audit'
    | '/dashboard'
    | '/organizations'
    | '/rbac'
    | '/support'
    | '/terms'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_public/change-password'
    | '/_public/login'
    | '/_public/'
    | '/_protected/announcements/'
    | '/_protected/audit/'
    | '/_protected/dashboard/'
    | '/_protected/organizations/'
    | '/_protected/rbac/'
    | '/_protected/support/'
    | '/_protected/terms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/change-password': {
      id: '/_public/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof PublicChangePasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/terms/': {
      id: '/_protected/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof ProtectedTermsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/support/': {
      id: '/_protected/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof ProtectedSupportIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/rbac/': {
      id: '/_protected/rbac/'
      path: '/rbac'
      fullPath: '/rbac/'
      preLoaderRoute: typeof ProtectedRbacIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organizations/': {
      id: '/_protected/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof ProtectedOrganizationsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/audit/': {
      id: '/_protected/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof ProtectedAuditIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/announcements/': {
      id: '/_protected/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof ProtectedAnnouncementsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAnnouncementsIndexRoute: typeof ProtectedAnnouncementsIndexRoute
  ProtectedAuditIndexRoute: typeof ProtectedAuditIndexRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedOrganizationsIndexRoute: typeof ProtectedOrganizationsIndexRoute
  ProtectedRbacIndexRoute: typeof ProtectedRbacIndexRoute
  ProtectedSupportIndexRoute: typeof ProtectedSupportIndexRoute
  ProtectedTermsIndexRoute: typeof ProtectedTermsIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAnnouncementsIndexRoute: ProtectedAnnouncementsIndexRoute,
  ProtectedAuditIndexRoute: ProtectedAuditIndexRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedOrganizationsIndexRoute: ProtectedOrganizationsIndexRoute,
  ProtectedRbacIndexRoute: ProtectedRbacIndexRoute,
  ProtectedSupportIndexRoute: ProtectedSupportIndexRoute,
  ProtectedTermsIndexRoute: ProtectedTermsIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicChangePasswordRoute: typeof PublicChangePasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicChangePasswordRoute: PublicChangePasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
