apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-cluster.yaml # 오퍼레이터 리소스 (마스터 파일)
  - postgres-config.yaml
  - postgres-secret.yaml
  - postgres-backup-storage.yaml
  - postgres-backup-cronjob.yaml
