apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: dev-infra
spec:
  instances: 1
  bootstrap:
    initdb:
      database: platform_db
      owner: postgres
      secret:
        name: postgres-secret
  storage:
    size: 5Gi
