import { Activity, Bell, BookOpen, Box, Briefcase, Calendar, Database, FileText,
         Folder, Globe, Heart, Home, Image, Key, LayoutDashboard, Lock,
         type LucideIcon, Mail, MessageSquare, Server, Settings, Shield, ShoppingBag,
         ShoppingCart, Star, Users } from 'lucide-react';

export const COMMON_ICONS: Array<{ name: string, icon: LucideIcon }> = [
  { name: 'Home', icon: Home },
  { name: 'LayoutDashboard', icon: LayoutDashboard },
  { name: 'Users', icon: Users },
  { name: 'Settings', icon: Settings },
  { name: 'Folder', icon: Folder },
  { name: 'FileText', icon: FileText },
  { name: 'Database', icon: Database },
  { name: 'Shield', icon: Shield },
  { name: 'Activity', icon: Activity },
  { name: 'Box', icon: Box },
  { name: 'Image', icon: Image },
  { name: 'Mail', icon: Mail },
  { name: 'MessageSquare', icon: MessageSquare },
  { name: 'ShoppingBag', icon: ShoppingBag },
  { name: 'ShoppingCart', icon: ShoppingCart },
  { name: 'Star', icon: Star },
  { name: 'Heart', icon: Heart },
  { name: 'Calendar', icon: Calendar },
  { name: 'Bell', icon: Bell },
  { name: 'BookOpen', icon: BookOpen },
  { name: 'Briefcase', icon: Briefcase },
  { name: 'Globe', icon: Globe },
  { name: 'Lock', icon: Lock },
  { name: 'Key', icon: Key },
  { name: 'Server', icon: Server },
];
