apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: monitoring-grafana-vs
  namespace: monitoring
spec:
  hosts:
  - "grafana.local"
  gateways:
  - monitoring-grafana-gw
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: grafana.monitoring.svc.cluster.local
        port:
          number: 3000
