apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: dev-infra
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  RABBITMQ_ERLANG_COOKIE: rabbitmq-cookie-dev
