apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: dev-infra
type: Opaque
stringData:
  username: guest
  password: guest
  default_user.conf: |
    default_user = guest
    default_pass = guest
  RABBITMQ_ERLANG_COOKIE: rabbitmq-cookie-dev
