apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: dev-infra
  labels:
    app: rabbitmq
spec:
  serviceName: "rabbitmq"
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999 # 'rabbitmq' user in some images has UID 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 60
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        envFrom:
        - secretRef:
            name: rabbitmq-secret
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        startupProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 36
          timeoutSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 6
          timeoutSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 60
          periodSeconds: 20
          failureThreshold: 6
          timeoutSeconds: 3
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
