apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: dev-infra
type: Opaque
stringData:
  username: dev_rabbitmq_user
  password: dev_rabbitmq_password
  default_user.conf: |
    default_user = dev_rabbitmq_user
    default_pass = dev_rabbitmq_password
  RABBITMQ_ERLANG_COOKIE: rabbitmq-cookie-dev
