apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform-service-cm.yaml
  - platform-service-secret.yaml
  - platform-service-deploy.yaml
  - platform-service-svc.yaml
