apiVersion: v1
kind: Service
metadata:
  name: platform-service
  namespace: dev-service
  labels:
    app.kubernetes.io/name: platform-service
    app.kubernetes.io/part-of: ai-base-app
spec:
  selector:
    app.kubernetes.io/name: platform-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
