apiVersion: v1
kind: Secret
metadata:
  name: platform-service-secret
  namespace: dev-service
  labels:
    app.kubernetes.io/name: platform-service
    app.kubernetes.io/part-of: ai-base-app
type: Opaque
stringData:
  DATABASE_URL: "postgresql://platform_user:postgrespassword@postgres-rw.dev-infra.svc.cluster.local:5432/platform_db"
  REDIS_URL: "redis://default:dev_redis_password@redis-leader.dev-infra.svc.cluster.local:6379"
  RABBITMQ_URL: "amqp://dev_rabbitmq_user:dev_rabbitmq_password@rabbitmq.dev-infra.svc.cluster.local:5672?frameMax=8192"
  SESSION_SECRET: "dev_session_secret_key_1234567890"
  JWT_ACCESS_SECRET: "dev_access_secret_key_1234567890"
  JWT_REFRESH_SECRET: "dev_refresh_secret_key_1234567890"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_SECURE: "false"
  MAIL_USER: "wlsyong90.dev@gmail.com"
  MAIL_PASS: "lgfbcovasdqgmshf"
