apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: redis
  namespace: dev-infra
spec:
  clusterSize: 3 # OpsTree Sentinel/Cluster 구성을 위한 사이즈
  kubernetesConfig:
    image: public.ecr.aws/bitnami/redis@sha256:204a12ace951df11e155b8570ecf215b3975b1496cc0da6edacca531fc2286cc
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
