apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: redis
  namespace: dev-infra
spec:
  clusterSize: 1 # dev 단일 인스턴스 구성
  kubernetesConfig:
    image: redis:7
    imagePullPolicy: IfNotPresent
    redisSecret:
      name: redis-secret
      key: password
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
