apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: dev-infra
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: ai-base-app
spec:
  kafka:
    version: 3.6.0
    replicas: 1 # dev 단일 브로커 구성
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.6"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        deleteClaim: false
    # KRaft 모드 활성화 (고도화 도구)
    metadataVersion: "3.6-IV2"
  entityOperator:
    topicOperator: {}
    userOperator: {}
