apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-gateway-from-istio-ingress
  namespace: dev-web
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: platform-gateway
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: istio-system
      podSelector:
        matchLabels:
          istio: ingress
    ports:
    - protocol: TCP
      port: 3000
