apiVersion: v1
kind: ConfigMap
metadata:
  name: service-gateway-config
  namespace: dev-web
data:
  RABBITMQ_URL: "amqp://rabbitmq.dev-infra.svc.cluster.local:5672"
  NODE_ENV: "development"
  PORT: "3000"
