apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-gateway
  namespace: dev-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-gateway
  template:
    metadata:
      labels:
        app: service-gateway
    spec:
      containers:
      - name: service-gateway
        image: service-gateway:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        envFrom:
        - configMapRef:
            name: service-gateway-config
        ports:
        - containerPort: 3000
