apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-gateway-hpa
  namespace: dev-web
  labels:
    app.kubernetes.io/name: service-gateway
    app.kubernetes.io/part-of: ai-base-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-gateway-deploy
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
