apiVersion: v1
kind: Service
metadata:
  name: service-gateway
  namespace: dev-web
spec:
  type: ClusterIP  # 다시 내부용으로 변경
  selector:
    app: service-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
