apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-platform-auth-from-service-gateway
  namespace: dev-api
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: platform-auth-service
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: dev-web
      podSelector:
        matchLabels:
          app.kubernetes.io/name: service-gateway
    ports:
    - protocol: TCP
      port: 3001
