/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

export interface AgreeTermsRequestDto {
  /** 멤버 식별자 */
  memberId: string;
  /** 동의할 약관 버전 식별자 */
  termsVersionId: string;
}
