/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export type AnnouncementsControllerGetAnnouncementsV1Params = {
/**
 * 게시 확정된 공지사항만 조회 여부
 */
isPublishedOnly?: boolean;
};
