/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */
import type { AnnouncementControllerGetAnnouncementsV1DirectionItem } from './announcementControllerGetAnnouncementsV1DirectionItem';
import type { GetAnnouncementPageFilters } from './getAnnouncementPageFilters';

export type AnnouncementControllerGetAnnouncementsV1Params = {
/**
 * 필터 조건
 */
filter: GetAnnouncementPageFilters;
/**
 * 정렬 필드
 */
sort?: string[];
/**
 * 정렬 방향
 */
direction?: AnnouncementControllerGetAnnouncementsV1DirectionItem[];
/**
 * 페이지 번호
 */
page?: unknown;
/**
 * 페이지 크기
 */
limit?: unknown;
};
