/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

export type AnnouncementControllerGetAnnouncementsV1DirectionItem = typeof AnnouncementControllerGetAnnouncementsV1DirectionItem[keyof typeof AnnouncementControllerGetAnnouncementsV1DirectionItem];


export const AnnouncementControllerGetAnnouncementsV1DirectionItem = {
  asc: 'asc',
  desc: 'desc',
} as const;
