/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { ApiResponseData } from './apiResponseData';
import type { ErrorInfo } from './errorInfo';

export interface ApiResponse {
  /** 성공 여부 */
  success: boolean;
  /** 응답 데이터 */
  data: ApiResponseData;
  /** 에러 상세 정보 */
  error?: ErrorInfo;
  /** 응답 메시지 */
  message?: string;
  /** 추적 ID */
  traceId: string;
  /** 요청 ID */
  requestId: string;
}
