/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 계정 잠금 해제 시각
 * @nullable
 */
export type AuthAccountInfoDtoLockUntil = { [key: string]: unknown } | null;
