/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 멤버 상태
 */
export type AuthMemberInfoDtoStatus = typeof AuthMemberInfoDtoStatus[keyof typeof AuthMemberInfoDtoStatus];


export const AuthMemberInfoDtoStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;
