/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { ApiResponse } from './apiResponse';
import type { AuthTokenResponseDto } from './authTokenResponseDto';

export type AuthControllerLoginV1200 = ApiResponse & {
  data?: AuthTokenResponseDto;
};
