/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { AuthUserInfoDto } from './authUserInfoDto';

export interface AuthMeResponseDto {
  /** 사용자 정보 */
  user: AuthUserInfoDto;
}
