/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export interface AuthUserInfoDto {
  /** 관리자 식별자 */
  id: string;
  /** 이메일 주소 */
  email: string;
  /** 관리자 상태 */
  status: string;
  /** 소속 조직 식별자 */
  organizationId?: string;
}
