/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export interface AuthTokenResponseDto {
  /** 액세스 토큰 */
  accessToken: string;
}
