/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { AuthAccountInfoDtoStatus } from './authAccountInfoDtoStatus';

export interface AuthAccountInfoDto {
  /** 계정 식별자 */
  id: string;
  /** 이메일 주소 */
  email: string;
  /** 계정 상태 */
  status: AuthAccountInfoDtoStatus;
  /** 마지막 로그인 일시 */
  lastLoginAt?: string;
  /** 비밀번호 만료 일시 */
  passwordExpiresAt: string;
  /** 잠금 해제 일시 */
  lockUntil?: string;
  /** 휴면 여부 */
  isDormant: boolean;
  /** 비밀번호 만료 여부 */
  isPasswordExpired: boolean;
}
