/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export interface AuthPermissionsResponseDto {
  /** 할당된 역할 코드 목록 */
  roles: string[];
  /** 할당된 권한 코드 목록 */
  permissions: string[];
}
