/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { AuthMemberInfoDtoStatus } from './authMemberInfoDtoStatus';

export interface AuthMemberInfoDto {
  /** 멤버 식별자 */
  id: string;
  /** 멤버 이름 */
  name: string;
  /** 멤버 상태 */
  status: AuthMemberInfoDtoStatus;
}
