/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 권한별 메타데이터 (UI 설정 등)
 */
export type AuthPermissionsResponseDtoMetadata = {[key: string]: { [key: string]: unknown }};
