/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { AuthOrganizationInfoDtoStatus } from './authOrganizationInfoDtoStatus';

export interface AuthOrganizationInfoDto {
  /** 조직 식별자 */
  id: string;
  /** 조직 코드 */
  code: string;
  /** 조직명 */
  name: string;
  /** 조직 이메일 */
  email: string;
  /** 조직 상태 */
  status: AuthOrganizationInfoDtoStatus;
}
