/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { AuthAccountInfoDto } from './authAccountInfoDto';
import type { AuthMemberInfoDto } from './authMemberInfoDto';
import type { AuthOrganizationInfoDto } from './authOrganizationInfoDto';

export interface AuthMeUserDto {
  /** 계정 정보 */
  account: AuthAccountInfoDto;
  /** 멤버 정보 */
  member: AuthMemberInfoDto;
  /**
     * 조직 정보
     * @nullable
     */
  organization: AuthOrganizationInfoDto | null;
  /** 권한 목록 */
  permissions: string[];
  /** 비밀번호 변경 필요 여부 */
  mustChangePassword: boolean;
}
