/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export interface AuthUserInfoDto {
  /** 관리자 고유 ID */
  id: string;
  /** 이메일 주소 */
  email: string;
  /** 관리자 상태 (ACTIVE, INACTIVE) */
  status: string;
  /** 소속 테넌트(조직) ID */
  tenantId?: string;
}
