/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 조직 상태
 */
export type AuthOrganizationInfoDtoStatus = typeof AuthOrganizationInfoDtoStatus[keyof typeof AuthOrganizationInfoDtoStatus];


export const AuthOrganizationInfoDtoStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  REJECTED: 'REJECTED',
} as const;
