/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export type CoreControllerGetActiveTermsV1Params = {
/**
 * ORGANIZATION 그룹 약관 조회 시 조직 ID
 */
organizationId?: string;
};
