/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { CoreControllerGetTicketsV1Status } from './coreControllerGetTicketsV1Status';

export type CoreControllerGetTicketsV1Params = {
/**
 * 조직 식별자 필터
 */
organizationId?: string;
/**
 * 티켓 상태 필터
 */
status?: CoreControllerGetTicketsV1Status;
};
