/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { CoreControllerGetOrganizationsV1Status } from './coreControllerGetOrganizationsV1Status';

export type CoreControllerGetOrganizationsV1Params = {
/**
 * 조직 상태 필터
 */
status?: CoreControllerGetOrganizationsV1Status;
};
