/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export type CoreControllerGetOrganizationsV1Status = typeof CoreControllerGetOrganizationsV1Status[keyof typeof CoreControllerGetOrganizationsV1Status];


export const CoreControllerGetOrganizationsV1Status = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  DORMANT: 'DORMANT',
} as const;
