/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { AnnouncementResponseDto } from './announcementResponseDto';
import type { ApiResponse } from './apiResponse';

export type CoreControllerCreateAnnouncementV1200 = ApiResponse & {
  data?: AnnouncementResponseDto;
};
