/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export type CoreControllerGetTicketsV1Status = typeof CoreControllerGetTicketsV1Status[keyof typeof CoreControllerGetTicketsV1Status];


export const CoreControllerGetTicketsV1Status = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
} as const;
