/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export type CoreControllerGetActiveTermsV1Params = {
/**
 * 조직별 약관 조회 시 조직 ID (미입력 시 플랫폼 공통 약관 포함 조회)
 */
organizationId?: string;
};
