/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { CreateTermsDocumentDtoScope } from './createTermsDocumentDtoScope';

export interface CreateTermsDocumentDto {
  /** 약관 문서 코드 */
  code: string;
  /** 약관 문서 제목 */
  title: string;
  /** 필수 약관 여부 */
  required: boolean;
  /** 생성 scope */
  scope: CreateTermsDocumentDtoScope;
}
