/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 버전 상태
 */
export type CreateTermsVersionDtoStatus = typeof CreateTermsVersionDtoStatus[keyof typeof CreateTermsVersionDtoStatus];


export const CreateTermsVersionDtoStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
} as const;
