/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 생성 scope
 */
export type CreateTermsDocumentDtoScope = typeof CreateTermsDocumentDtoScope[keyof typeof CreateTermsDocumentDtoScope];


export const CreateTermsDocumentDtoScope = {
  platform: 'platform',
  organization: 'organization',
} as const;
