/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { CreateTermsVersionDtoStatus } from './createTermsVersionDtoStatus';

export interface CreateTermsVersionDto {
  termsDocumentId: string;
  label: string;
  content: string;
  /** 효력 발생일 (미입력 시 현재 시간) */
  effectiveFrom?: string;
  /** 효력 종료일 (미입력 시 무제한) */
  effectiveTo?: string;
  /** 약관 버전 상태 (미입력 시 DRAFT) */
  status?: CreateTermsVersionDtoStatus;
}
