/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export interface CreateAnnouncementDto {
  /** 공지사항 제목 */
  title: string;
  /** 공지사항 내용 */
  content: string;
  /** 즉시 게시 여부 */
  isPublished?: boolean;
}
