/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { CreateAnnouncementDtoAudience } from './createAnnouncementDtoAudience';
import type { CreateAnnouncementDtoCategory } from './createAnnouncementDtoCategory';
import type { CreateAnnouncementDtoChannel } from './createAnnouncementDtoChannel';
import type { CreateAnnouncementDtoPriority } from './createAnnouncementDtoPriority';

export interface CreateAnnouncementDto {
  /** 공지사항 식별자 */
  id?: string;
  /** 공지사항 제목 */
  title: string;
  /** 공지사항 본문 */
  content: string;
  /** 공지 분류 */
  category?: CreateAnnouncementDtoCategory;
  /** 공지 대상 */
  audience?: CreateAnnouncementDtoAudience;
  /** 공지 채널 */
  channel?: CreateAnnouncementDtoChannel;
  /** 공지 우선순위 */
  priority?: CreateAnnouncementDtoPriority;
  /** 상단 고정 여부 */
  pinned?: boolean;
  /** 게시 확정 일시 */
  publishedAt?: string;
  /** 게시 시작일 */
  startAt?: string;
  /** 게시 종료일 */
  endAt?: string;
}
