/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 동의할 약관 버전
 */
export type CreateTermsAgreementRequestDtoTermsVersion = { [key: string]: unknown };
