/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { CreateInviteDtoRole } from './createInviteDtoRole';

export interface CreateInviteDto {
  /** 초대할 사람 이름 */
  name: string;
  /** 초대할 사람 이메일 */
  email: string;
  /** 부여할 역할 */
  role: CreateInviteDtoRole;
  /** 메모/메모사항 */
  note?: string;
}
