/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { CreateTermsVersionDtoStatus } from './createTermsVersionDtoStatus';

export interface CreateTermsVersionDto {
  /** 약관 문서 식별자 */
  termsDocumentId: string;
  /** 약관 버전 라벨 */
  label: string;
  /** 약관 본문 */
  content: string;
  /** 효력 시작일 */
  effectiveFrom?: string;
  /** 효력 종료일 */
  effectiveTo?: string;
  /** 버전 상태 */
  status?: CreateTermsVersionDtoStatus;
}
