/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 약관 버전 상태 (미입력 시 DRAFT)
 */
export type CreateTermsVersionDtoStatus = typeof CreateTermsVersionDtoStatus[keyof typeof CreateTermsVersionDtoStatus];


export const CreateTermsVersionDtoStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  DEPRECATED: 'DEPRECATED',
} as const;
