/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export type CreateResourceBatchItemDtoOperation = typeof CreateResourceBatchItemDtoOperation[keyof typeof CreateResourceBatchItemDtoOperation];


export const CreateResourceBatchItemDtoOperation = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
} as const;
