/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

export interface CreateTermsDocumentRequestDto {
  /** 약관 코드 */
  code: string;
  /** 약관 제목 */
  title: string;
  /** 필수 동의 여부 */
  required?: boolean;
  /** 약관 범위 (platform 또는 organization) */
  scope: string;
}
