/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 효력 일시
 * @nullable
 */
export type CreateTermsVersionRequestDtoEffectiveAt = { [key: string]: unknown } | null;
