/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export interface CreatePermissionSetDto {
  /** 권한 세트 코드 */
  code: string;
  /** 권한 세트 이름 */
  name: string;
  /** 권한 세트 설명 */
  description?: string;
  /** 복사할 권한 세트 식별자 */
  copyFromId?: string;
}
