/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { CreateResourceBatchItemDtoOperation } from './createResourceBatchItemDtoOperation';
import type { CreateResourceBatchItemDtoTranslations } from './createResourceBatchItemDtoTranslations';
import type { CreateResourceBatchItemDtoType } from './createResourceBatchItemDtoType';

export interface CreateResourceBatchItemDto {
  operation: CreateResourceBatchItemDtoOperation;
  tempId?: string;
  id?: string;
  code?: string;
  name?: string;
  type?: CreateResourceBatchItemDtoType;
  parentTempId?: string;
  path?: string;
  icon?: string;
  parentId?: string;
  sortOrder?: number;
  translations?: CreateResourceBatchItemDtoTranslations;
  actions?: string[];
}
