/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { CreateResourceDtoType } from './createResourceDtoType';

export interface CreateResourceDto {
  /** 리소스 코드 */
  code: string;
  /** 리소스 이름 */
  name: string;
  /** 리소스 유형 */
  type: CreateResourceDtoType;
  /** 리소스 경로 */
  path?: string;
  /** 아이콘 이름 */
  icon?: string;
  /** 부모 리소스 식별자 */
  parentId?: string;
}
