/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */
import type { CreateResourceRequestDtoType } from './createResourceRequestDtoType';

export interface CreateResourceRequestDto {
  /** 리소스 코드 */
  code: string;
  /** 리소스 이름 */
  name: string;
  /** 리소스 유형 */
  type: CreateResourceRequestDtoType;
  /** 리소스 경로 */
  path?: string;
  /** 부모 리소스 식별자 */
  parentId?: string;
}
