/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

export interface DeleteTermsDocumentDto {
  /** 약관 문서 식별자 */
  id: string;
}
