/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { ErrorInfoDetails } from './errorInfoDetails';

export interface ErrorInfo {
  /** 에러 코드 */
  code: string;
  /** 에러 메시지 */
  message: string | string[];
  /** 상세 정보 */
  details?: ErrorInfoDetails;
  /** HTTP 상태 코드 */
  status: number;
}
