/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */
import type { GetAnnouncementPageFiltersStatus } from './getAnnouncementPageFiltersStatus';

export interface GetAnnouncementPageFilters {
  /** 게시된 공지만 조회할지 여부 */
  isPublished?: boolean;
  /** 게시 상태 */
  status?: GetAnnouncementPageFiltersStatus;
}
