/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */
import type { GetOrganizationPageFiltersDtoStatus } from './getOrganizationPageFiltersDtoStatus';

export interface GetOrganizationPageFiltersDto {
  /** 메타데이터 날짜로 유추되는 조직 상태 필터 */
  status?: GetOrganizationPageFiltersDtoStatus;
}
