/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 티켓 상태 필터
 */
export type GetTicketPageFiltersDtoStatus = typeof GetTicketPageFiltersDtoStatus[keyof typeof GetTicketPageFiltersDtoStatus];


export const GetTicketPageFiltersDtoStatus = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
} as const;
