/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { HealthControllerReady503Details } from './healthControllerReady503Details';
import type { HealthControllerReady503Error } from './healthControllerReady503Error';
import type { HealthControllerReady503Info } from './healthControllerReady503Info';

export type HealthControllerReady503 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerReady503Info;
  /** @nullable */
  error?: HealthControllerReady503Error;
  details?: HealthControllerReady503Details;
};
