/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { HealthControllerLive503Details } from './healthControllerLive503Details';
import type { HealthControllerLive503Error } from './healthControllerLive503Error';
import type { HealthControllerLive503Info } from './healthControllerLive503Info';

export type HealthControllerLive503 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerLive503Info;
  /** @nullable */
  error?: HealthControllerLive503Error;
  details?: HealthControllerLive503Details;
};
