/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { HealthControllerLive200Details } from './healthControllerLive200Details';
import type { HealthControllerLive200Error } from './healthControllerLive200Error';
import type { HealthControllerLive200Info } from './healthControllerLive200Info';

export type HealthControllerLive200 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerLive200Info;
  /** @nullable */
  error?: HealthControllerLive200Error;
  details?: HealthControllerLive200Details;
};
