/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

export type I18nControllerGetTranslationsV1Params = {
/**
 * 조회할 번역 키 목록
 */
keys?: string;
/**
 * 선택 조회할 네임스페이스
 */
namespace?: string;
/**
 * 배치 조회할 로케일 목록
 */
locale?: string;
};
