/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { InviteResponseDtoInviteStatus } from './inviteResponseDtoInviteStatus';
import type { InviteResponseDtoLastLoginAt } from './inviteResponseDtoLastLoginAt';
import type { InviteResponseDtoMailDeliveryStatus } from './inviteResponseDtoMailDeliveryStatus';
import type { InviteResponseDtoRole } from './inviteResponseDtoRole';
import type { InviteResponseDtoStatus } from './inviteResponseDtoStatus';

export interface InviteResponseDto {
  /** 멤버 식별자 */
  id: string;
  /** 멤버 이름 */
  name: string;
  /** 멤버 상태 */
  status: InviteResponseDtoStatus;
  /** 생성자 식별자 */
  createdBy?: string;
  /** 메모 */
  note?: string;
  /** 이메일 */
  email: string;
  /** 권한 */
  role: InviteResponseDtoRole;
  /**
     * 최근 로그인
     * @nullable
     */
  lastLoginAt: InviteResponseDtoLastLoginAt;
  /** 초대 일시 (생성 시각 기준) */
  invitedAt: string;
  /** 메일 전송 상태 */
  mailDeliveryStatus?: InviteResponseDtoMailDeliveryStatus;
  /** 메일 큐 적재 시각 */
  mailDeliveryQueuedAt?: string;
  /** 메일 전송 성공 시각 */
  mailDeliverySentAt?: string;
  /** 메일 전송 실패 시각 */
  mailDeliveryFailedAt?: string;
  /** 현재 사용자 여부 */
  isMe: boolean;
  /** 초대 만료 시각 */
  expiresAt: string;
  /** 초대 상태 */
  inviteStatus: InviteResponseDtoInviteStatus;
}
