/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { InviteResponseDtoInviteStatus } from './inviteResponseDtoInviteStatus';
import type { InviteResponseDtoLastLoginAt } from './inviteResponseDtoLastLoginAt';
import type { InviteResponseDtoRole } from './inviteResponseDtoRole';
import type { InviteResponseDtoStatus } from './inviteResponseDtoStatus';

export interface InviteResponseDto {
  /** 멤버 식별자 */
  id: string;
  /** 이름 */
  name: string;
  /** 이메일 */
  email: string;
  /** 권한 */
  role: InviteResponseDtoRole;
  /** 멤버 상태 */
  status: InviteResponseDtoStatus;
  /**
     * 최근 로그인
     * @nullable
     */
  lastLoginAt: InviteResponseDtoLastLoginAt;
  /** 초대 일시 */
  invitedAt: string;
  /** 초대한 사람 */
  invitedBy: string;
  /** 메모 */
  note?: string;
  /** 현재 사용자 여부 */
  isMe: boolean;
  /** 만료 일시 */
  expiresAt: string;
  /** 초대 상태 */
  inviteStatus: InviteResponseDtoInviteStatus;
}
