/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 메일 전송 상태
 */
export type InviteResponseDtoMailDeliveryStatus = typeof InviteResponseDtoMailDeliveryStatus[keyof typeof InviteResponseDtoMailDeliveryStatus];


export const InviteResponseDtoMailDeliveryStatus = {
  QUEUED: 'QUEUED',
  SENT: 'SENT',
  FAILED: 'FAILED',
} as const;
