/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { LocaleDto } from './localeDto';

export interface LocalesDataDto {
  /** 로케일 목록 */
  list: LocaleDto[];
}
