/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 문자 방향
 */
export type LocaleDtoDirection = typeof LocaleDtoDirection[keyof typeof LocaleDtoDirection];


export const LocaleDtoDirection = {
  ltr: 'ltr',
  rtl: 'rtl',
} as const;
