/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { LocaleDtoDirection } from './localeDtoDirection';

export interface LocaleDto {
  /** 로케일 코드 */
  code: string;
  /** 이름 */
  name: string;
  /** 지역 코드 */
  regionCode?: string;
  /** 문자 방향 */
  direction: LocaleDtoDirection;
  /** 활성화 여부 */
  isActive: boolean;
  /** 정렬 순서 */
  sortOrder: number;
}
