/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** 관리자 이메일 */
  email: string;
  /** 비밀번호 */
  password: string;
}
