/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { MembersControllerGetInvitesV1InviteStatus } from './membersControllerGetInvitesV1InviteStatus';
import type { MembersControllerGetInvitesV1Role } from './membersControllerGetInvitesV1Role';

export type MembersControllerGetInvitesV1Params = {
/**
 * 검색어
 */
search?: string;
/**
 * 초대 상태
 */
inviteStatus?: MembersControllerGetInvitesV1InviteStatus;
/**
 * 조직 역할
 */
role?: MembersControllerGetInvitesV1Role;
};
