/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */
import type { MembersControllerGetInvitesV1InviteStatus } from './membersControllerGetInvitesV1InviteStatus';

export type MembersControllerGetInvitesV1Params = {
/**
 * 검색어 (이름, 이메일, 역할 등)
 */
search?: string;
/**
 * 초대 상태 필터
 */
inviteStatus?: MembersControllerGetInvitesV1InviteStatus;
/**
 * 역할 식별자 필터
 */
roleId?: string;
};
