/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export type MembersControllerGetMembersV1Role = typeof MembersControllerGetMembersV1Role[keyof typeof MembersControllerGetMembersV1Role];


export const MembersControllerGetMembersV1Role = {
  OWNER: 'OWNER',
  MANAGER: 'MANAGER',
  VIEWER: 'VIEWER',
} as const;
