/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { MemberResponseDtoLastLoginAt } from './memberResponseDtoLastLoginAt';
import type { MemberResponseDtoMailDeliveryStatus } from './memberResponseDtoMailDeliveryStatus';
import type { MemberResponseDtoRole } from './memberResponseDtoRole';
import type { MemberResponseDtoStatus } from './memberResponseDtoStatus';

export interface MemberResponseDto {
  /** 멤버 식별자 */
  id: string;
  /** 이름 */
  name: string;
  /** 이메일 */
  email: string;
  /** 권한 */
  role: MemberResponseDtoRole;
  /** 멤버 상태 */
  status: MemberResponseDtoStatus;
  /**
     * 최근 로그인
     * @nullable
     */
  lastLoginAt: MemberResponseDtoLastLoginAt;
  /** 초대 일시 (생성 시각 기준) */
  invitedAt: string;
  /** 초대한 사람 */
  createdBy?: string;
  /** 메모 */
  note?: string;
  /** 메일 전송 상태 */
  mailDeliveryStatus?: MemberResponseDtoMailDeliveryStatus;
  /** 메일 큐 적재 시각 */
  mailDeliveryQueuedAt?: string;
  /** 메일 전송 성공 시각 */
  mailDeliverySentAt?: string;
  /** 메일 전송 실패 시각 */
  mailDeliveryFailedAt?: string;
  /** 현재 사용자 여부 */
  isMe: boolean;
}
