/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 최근 로그인
 * @nullable
 */
export type MemberResponseDtoLastLoginAt = { [key: string]: unknown } | null;
