/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export interface MemberTermsConsentResponseDto {
  /** 동의 식별자 */
  id: string;
  /** 동의 여부 */
  agreed: boolean;
  /** 동의 일시 */
  agreedAt: string;
}
