/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */
import type { MembersControllerGetMembersV1Status } from './membersControllerGetMembersV1Status';

export type MembersControllerGetMembersV1Params = {
/**
 * 검색어
 */
search?: string;
/**
 * 멤버 상태
 */
status?: MembersControllerGetMembersV1Status;
/**
 * 조직 역할
 */
role?: string;
};
