/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export type MembersControllerGetInvitesV1Role = typeof MembersControllerGetInvitesV1Role[keyof typeof MembersControllerGetInvitesV1Role];


export const MembersControllerGetInvitesV1Role = {
  OWNER: 'OWNER',
  MANAGER: 'MANAGER',
  VIEWER: 'VIEWER',
} as const;
