/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

export type MembersControllerGetInvitesV1InviteStatus = typeof MembersControllerGetInvitesV1InviteStatus[keyof typeof MembersControllerGetInvitesV1InviteStatus];


export const MembersControllerGetInvitesV1InviteStatus = {
  QUEUED: 'QUEUED',
  PENDING: 'PENDING',
  EXPIRED: 'EXPIRED',
  CANCELED: 'CANCELED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
} as const;
