/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export type OrganizationResponseDtoStatus = typeof OrganizationResponseDtoStatus[keyof typeof OrganizationResponseDtoStatus];


export const OrganizationResponseDtoStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  DORMANT: 'DORMANT',
} as const;
