/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { OrganizationResponseDtoStatus } from './organizationResponseDtoStatus';

export interface OrganizationResponseDto {
  id: string;
  name: string;
  subdomain: string;
  status: OrganizationResponseDtoStatus;
  createdAt: string;
}
