/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

export interface OrganizationControllerGetOrganizationRolesV1Item {
  id: string;
  code: string;
  name: string;
  description?: string;
}

export type OrganizationControllerGetOrganizationRolesV1 = OrganizationControllerGetOrganizationRolesV1Item[];
