/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { OrganizationsControllerGetOrganizationsV1Status } from './organizationsControllerGetOrganizationsV1Status';

export type OrganizationsControllerGetOrganizationsV1Params = {
/**
 * 조직 상태 필터
 */
status?: OrganizationsControllerGetOrganizationsV1Status;
};
