/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */
import type { OrganizationControllerGetOrganizationsV1Status } from './organizationControllerGetOrganizationsV1Status';

export type OrganizationControllerGetOrganizationsV1Params = {
/**
 * 조직 상태 필터
 */
status?: OrganizationControllerGetOrganizationsV1Status;
};
