/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

export type OrganizationControllerGetOrganizationsV1Status = typeof OrganizationControllerGetOrganizationsV1Status[keyof typeof OrganizationControllerGetOrganizationsV1Status];


export const OrganizationControllerGetOrganizationsV1Status = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  REJECTED: 'REJECTED',
} as const;
