/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export interface PermissionSetResponseDto {
  /** 권한 세트 식별자 */
  id: string;
  /** 권한 세트 코드 */
  code: string;
  /** 권한 세트 이름 */
  name: string;
  /** 권한 세트 설명 */
  description?: string;
  /** 배정된 관리자 수 */
  assignmentCount: number;
  /** 활성 여부 */
  isActive: boolean;
  /** 권한 코드 목록 */
  permissionCodes: string[];
}
