/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { ApiResponse } from './apiResponse';
import type { ResourceResponseDto } from './resourceResponseDto';

export type RbacControllerGetResourcesV1200 = ApiResponse & {
  data?: ResourceResponseDto[];
};
