/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { ApiResponse } from './apiResponse';
import type { RoleResponseDto } from './roleResponseDto';

export type RbacControllerGetRolesV1200 = ApiResponse & {
  data?: RoleResponseDto[];
};
