/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */
import type { ResourceControllerGetResourcesV1Scope } from './resourceControllerGetResourcesV1Scope';

export type ResourceControllerGetResourcesV1Params = {
/**
 * 리소스 관리 범위
 */
scope: ResourceControllerGetResourcesV1Scope;
};
