/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 리소스 관리 범위
 */
export type ResourceResponseDtoScope = typeof ResourceResponseDtoScope[keyof typeof ResourceResponseDtoScope];


export const ResourceResponseDtoScope = {
  PLATFORM: 'PLATFORM',
  ORGANIZATION: 'ORGANIZATION',
} as const;
