/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 리소스 범위
 */
export type ResourceDetailResponseDtoScope = typeof ResourceDetailResponseDtoScope[keyof typeof ResourceDetailResponseDtoScope];


export const ResourceDetailResponseDtoScope = {
  PLATFORM: 'PLATFORM',
  ORGANIZATION: 'ORGANIZATION',
} as const;
