/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

export type ResourceControllerGetResourcesV1Scope = typeof ResourceControllerGetResourcesV1Scope[keyof typeof ResourceControllerGetResourcesV1Scope];


export const ResourceControllerGetResourcesV1Scope = {
  PLATFORM: 'PLATFORM',
  ORGANIZATION: 'ORGANIZATION',
} as const;
