/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 리소스 유형
 */
export type ResourceDetailResponseDtoType = typeof ResourceDetailResponseDtoType[keyof typeof ResourceDetailResponseDtoType];


export const ResourceDetailResponseDtoType = {
  MENU: 'MENU',
  API: 'API',
  COMPONENT: 'COMPONENT',
} as const;
