/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { ResourceDetailResponseDtoScope } from './resourceDetailResponseDtoScope';
import type { ResourceDetailResponseDtoType } from './resourceDetailResponseDtoType';

export interface ResourceDetailResponseDto {
  /** 리소스 식별자 */
  id: string;
  /** 리소스 코드 */
  code: string;
  /** 리소스 이름 */
  name: string;
  /** 리소스 유형 */
  type: ResourceDetailResponseDtoType;
  /** 리소스 관리 범위 */
  scope: ResourceDetailResponseDtoScope;
  /** 리소스 경로 */
  path?: string;
  /** 아이콘 */
  icon?: string;
  /** 정렬 순서 */
  sortOrder?: number;
  /** 리소스 액션 목록 */
  actions: string[];
  /** 제약 조건 */
  constraint?: string;
  /** 부모 리소스 식별자 */
  parentId?: string;
}
