/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { ResourceResponseDtoType } from './resourceResponseDtoType';

export interface ResourceResponseDto {
  id: string;
  code: string;
  name: string;
  type: ResourceResponseDtoType;
  path?: string;
  icon?: string;
  sortOrder?: number;
  actions: string[];
  mappedAction?: string;
  children: ResourceResponseDto[];
}
