/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { RoleResponseDtoScope } from './roleResponseDtoScope';

export interface RoleResponseDto {
  id: string;
  code: string;
  name: string;
  scope: RoleResponseDtoScope;
  description?: string;
}
