/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 공지 분류
 */
export type SaveAnnouncementRequestDtoCategory = typeof SaveAnnouncementRequestDtoCategory[keyof typeof SaveAnnouncementRequestDtoCategory];


export const SaveAnnouncementRequestDtoCategory = {
  NOTICE: 'NOTICE',
  MAINTENANCE: 'MAINTENANCE',
  SECURITY: 'SECURITY',
  EVENT: 'EVENT',
} as const;
