/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */
import type { SaveAnnouncementRequestDtoAudience } from './saveAnnouncementRequestDtoAudience';
import type { SaveAnnouncementRequestDtoCategory } from './saveAnnouncementRequestDtoCategory';
import type { SaveAnnouncementRequestDtoChannel } from './saveAnnouncementRequestDtoChannel';
import type { SaveAnnouncementRequestDtoPriority } from './saveAnnouncementRequestDtoPriority';

export interface SaveAnnouncementRequestDto {
  /** 공지사항 식별자 */
  id?: string;
  /** 공지사항 제목 */
  title: string;
  /** 공지사항 본문 */
  content: string;
  /** 공지 분류 */
  category?: SaveAnnouncementRequestDtoCategory;
  /** 공지 대상 */
  audience?: SaveAnnouncementRequestDtoAudience;
  /** 공지 채널 */
  channel?: SaveAnnouncementRequestDtoChannel;
  /** 공지 우선순위 */
  priority?: SaveAnnouncementRequestDtoPriority;
  /** 게시 유무 */
  isPublished?: boolean;
  /** 게시 확정 일시 */
  publishedAt?: string;
  /** 게시 시작일 */
  startAt?: string;
  /** 게시 종료일 */
  endAt?: string;
}
