/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 공지 채널
 */
export type SaveAnnouncementRequestDtoChannel = typeof SaveAnnouncementRequestDtoChannel[keyof typeof SaveAnnouncementRequestDtoChannel];


export const SaveAnnouncementRequestDtoChannel = {
  IN_APP: 'IN_APP',
  EMAIL: 'EMAIL',
  PUSH: 'PUSH',
} as const;
