/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

export type SupportControllerGetTicketsV1Status = typeof SupportControllerGetTicketsV1Status[keyof typeof SupportControllerGetTicketsV1Status];


export const SupportControllerGetTicketsV1Status = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
} as const;
