/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

export type SupportControllerGetTicketsV1DirectionItem = typeof SupportControllerGetTicketsV1DirectionItem[keyof typeof SupportControllerGetTicketsV1DirectionItem];


export const SupportControllerGetTicketsV1DirectionItem = {
  asc: 'asc',
  desc: 'desc',
} as const;
