/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */
import type { GetTicketPageFiltersDto } from './getTicketPageFiltersDto';
import type { SupportControllerGetTicketsV1DirectionItem } from './supportControllerGetTicketsV1DirectionItem';

export type SupportControllerGetTicketsV1Params = {
/**
 * 정렬 필드
 */
sort?: string[];
/**
 * 정렬 방향
 */
direction?: SupportControllerGetTicketsV1DirectionItem[];
/**
 * 페이지 번호
 */
page?: number;
/**
 * 페이지 크기
 */
limit?: number;
/**
 * 필터 조건
 */
filters?: GetTicketPageFiltersDto;
};
