/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { TermsVersionResponseDtoStatus } from './termsVersionResponseDtoStatus';

export interface TermsVersionResponseDto {
  id: string;
  versionLabel: string;
  content: string;
  status: TermsVersionResponseDtoStatus;
}
