/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 문서 상태
 */
export type TermsDocumentResponseDtoStatus = typeof TermsDocumentResponseDtoStatus[keyof typeof TermsDocumentResponseDtoStatus];


export const TermsDocumentResponseDtoStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
} as const;
