/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */
import type { TermsControllerGetTermsDocumentsV1Scope } from './termsControllerGetTermsDocumentsV1Scope';
import type { TermsControllerGetTermsDocumentsV1Status } from './termsControllerGetTermsDocumentsV1Status';

export type TermsControllerGetTermsDocumentsV1Params = {
/**
 * 조회 scope
 */
scope?: TermsControllerGetTermsDocumentsV1Scope;
/**
 * 상태 필터
 */
status?: TermsControllerGetTermsDocumentsV1Status;
/**
 * 검색어
 */
keyword?: string;
};
