/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { TermsVersionResponseDtoStatus } from './termsVersionResponseDtoStatus';

export interface TermsVersionResponseDto {
  /** 약관 버전 식별자 */
  id: string;
  /** 약관 내용 */
  content: string;
  /** 체크섬 */
  checksum: string;
  /** 버전 상태 */
  status: TermsVersionResponseDtoStatus;
  /** 효력 일시 */
  effectiveAt: string;
  /** 버전 라벨 */
  versionLabel: string;
}
