/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export type TermsControllerGetTermsDocumentsV1Status = typeof TermsControllerGetTermsDocumentsV1Status[keyof typeof TermsControllerGetTermsDocumentsV1Status];


export const TermsControllerGetTermsDocumentsV1Status = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  DEPRECATED: 'DEPRECATED',
  ACTIVE: 'ACTIVE',
  SCHEDULED_DEPRECATION: 'SCHEDULED_DEPRECATION',
} as const;
