/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

export type TermsControllerGetTermsDocumentVersionsV1Params = {
/**
 * 버전 검색어
 */
keyword?: string;
};
