/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export type TermsVersionResponseDtoStatus = typeof TermsVersionResponseDtoStatus[keyof typeof TermsVersionResponseDtoStatus];


export const TermsVersionResponseDtoStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED',
} as const;
