/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

export type TermsControllerGetTermsDocumentsV1Scope = typeof TermsControllerGetTermsDocumentsV1Scope[keyof typeof TermsControllerGetTermsDocumentsV1Scope];


export const TermsControllerGetTermsDocumentsV1Scope = {
  platform: 'platform',
  organization: 'organization',
} as const;
