/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { TermsDocumentResponseDtoStatus } from './termsDocumentResponseDtoStatus';

export interface TermsDocumentResponseDto {
  /** 약관 문서 식별자 */
  id: string;
  /** 약관 코드 */
  code: string;
  /** 약관 제목 */
  title: string;
  /** 필수 동의 여부 */
  required: boolean;
  /** 폐기 일시 */
  deprecatedAt?: string;
  /** 약관 상태 */
  status: TermsDocumentResponseDtoStatus;
  /**
     * 조직 식별자
     * @nullable
     */
  organizationId?: string | null;
}
