/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export type TermsDocumentResponseDtoGroupType = typeof TermsDocumentResponseDtoGroupType[keyof typeof TermsDocumentResponseDtoGroupType];


export const TermsDocumentResponseDtoGroupType = {
  PLATFORM: 'PLATFORM',
  ORGANIZATION: 'ORGANIZATION',
} as const;
