/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

export type TermsControllerGetTermsDocumentsV1Status = typeof TermsControllerGetTermsDocumentsV1Status[keyof typeof TermsControllerGetTermsDocumentsV1Status];


export const TermsControllerGetTermsDocumentsV1Status = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  TERMINATED: 'TERMINATED',
  ACTIVE: 'ACTIVE',
} as const;
