/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { TermsDocumentResponseDto } from './termsDocumentResponseDto';
import type { TermsVersionResponseDto } from './termsVersionResponseDto';

export interface TermsDocumentDetailResponseDto {
  /** 문서 기본 정보 */
  document: TermsDocumentResponseDto;
  /** 버전 목록 */
  versions: TermsVersionResponseDto[];
  /**
     * 현재 효력 중인 버전
     * @nullable
     */
  currentVersion?: TermsVersionResponseDto | null;
}
