/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { TermsDocumentResponseDtoGroupType } from './termsDocumentResponseDtoGroupType';
import type { TermsDocumentResponseDtoStatus } from './termsDocumentResponseDtoStatus';

export interface TermsDocumentResponseDto {
  id: string;
  groupType: TermsDocumentResponseDtoGroupType;
  code: string;
  title: string;
  required: boolean;
  status: TermsDocumentResponseDtoStatus;
}
