/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { TicketResponseDtoPriority } from './ticketResponseDtoPriority';
import type { TicketResponseDtoStatus } from './ticketResponseDtoStatus';

export interface TicketResponseDto {
  /** 티켓 식별자 */
  id: string;
  /** 티켓 제목 */
  title: string;
  /** 티켓 내용 */
  content: string;
  /** 티켓 상태 */
  status: TicketResponseDtoStatus;
  /** 티켓 우선순위 */
  priority: TicketResponseDtoPriority;
  /** 생성 일시 */
  createdAt: string;
  /** 조직 식별자 */
  organizationId: string;
}
