/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { TicketResponseDtoPriority } from './ticketResponseDtoPriority';
import type { TicketResponseDtoStatus } from './ticketResponseDtoStatus';

export interface TicketResponseDto {
  id: string;
  organizationId: string;
  title: string;
  content: string;
  status: TicketResponseDtoStatus;
  priority: TicketResponseDtoPriority;
  createdAt: string;
}
