/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { TranslationBulkOperationDto } from './translationBulkOperationDto';

export interface TranslationBulkDto {
  /** 번역 처리 목록 */
  operations: TranslationBulkOperationDto[];
}
