/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export interface TranslationUpdateDto {
  /** 번역 네임스페이스 */
  namespace: string;
  /** 번역 키 */
  key: string;
  /** 번역 로케일 */
  locale: string;
  /** 번역 값 */
  value: string;
}
