/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 처리 유형
 */
export type TranslationBulkOperationDtoAction = typeof TranslationBulkOperationDtoAction[keyof typeof TranslationBulkOperationDtoAction];


export const TranslationBulkOperationDtoAction = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
} as const;
