/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 버전 상태
 */
export type UpdateTermsVersionDtoStatus = typeof UpdateTermsVersionDtoStatus[keyof typeof UpdateTermsVersionDtoStatus];


export const UpdateTermsVersionDtoStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
} as const;
