/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */
import type { UpdateMemberStatusRequestDtoStatus } from './updateMemberStatusRequestDtoStatus';

export interface UpdateMemberStatusRequestDto {
  /** 멤버 식별자 */
  id: string;
  /** 변경할 상태 */
  status: UpdateMemberStatusRequestDtoStatus;
}
