/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export interface UpdateResourceSortItemDto {
  /** 리소스 식별자 */
  id: string;
  /** 정렬 순서 */
  sortOrder: number;
}
