/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export interface UpdateRolePermissionsDto {
  /** 역할에 부여할 권한 코드 배열 */
  permissionCodes: string[];
}
