/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export interface UpdatePermissionSetPermissionsDto {
  /** 권한 세트 식별자 */
  id: string;
  /** 부여할 권한 코드 목록 */
  permissionCodes: string[];
}
