/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import type { UpdateMemberRoleDtoRole } from './updateMemberRoleDtoRole';

export interface UpdateMemberRoleDto {
  /** 멤버 식별자 */
  id: string;
  /** 변경할 역할 */
  role: UpdateMemberRoleDtoRole;
}
