/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */
import type { UpdateResourceDetailBodyDtoScope } from './updateResourceDetailBodyDtoScope';

export interface UpdateResourceDetailBodyDto {
  /** 리소스 식별자 */
  id: string;
  /** 리소스 코드 */
  code: string;
  /** 리소스 이름 */
  name: string;
  /** 리소스 관리 범위 */
  scope: UpdateResourceDetailBodyDtoScope;
  /** 리소스 경로 */
  path?: string;
  /** 아이콘 */
  icon?: string;
}
