/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */
import type { UpdateTermsVersionRequestDtoEffectiveAt } from './updateTermsVersionRequestDtoEffectiveAt';

export interface UpdateTermsVersionRequestDto {
  /** 약관 버전 식별자 */
  id: string;
  /** 버전 라벨 */
  label: string;
  /** 약관 내용 */
  content: string;
  /**
     * 효력 일시
     * @nullable
     */
  effectiveAt?: UpdateTermsVersionRequestDtoEffectiveAt;
}
