/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */

/**
 * 변경할 상태
 */
export type UpdateMemberStatusRequestDtoStatus = typeof UpdateMemberStatusRequestDtoStatus[keyof typeof UpdateMemberStatusRequestDtoStatus];


export const UpdateMemberStatusRequestDtoStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;
