/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */

export interface UpdateResourceDetailBodyDto {
  /** 리소스 식별자 */
  id: string;
  /** 리소스 코드 */
  code: string;
  /** 리소스 이름 */
  name: string;
  /** 리소스 경로 */
  path?: string;
  /** 아이콘 이름 */
  icon?: string;
}
