apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform-gateway-deploy.yaml
  - platform-gateway-svc.yaml
  - platform-gateway-cm.yaml
  - platform-gateway-secret.yaml
  - platform-gateway-gw.yaml
  - platform-gateway-vs.yaml
