apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-gateway-cm
  namespace: dev-web
  labels:
    app.kubernetes.io/name: platform-gateway
    app.kubernetes.io/part-of: ai-base-app
data:
  NODE_ENV: "development"
  PORT: "3000"
  AUTH_SERVICE_URL: "platform-auth-service.dev-service.svc.cluster.local:3001"
  CORE_SERVICE_URL: "platform-core-service.dev-service.svc.cluster.local:3005"
  JWT_ACCESS_EXPIRES_IN: "3600"
