apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: platform-gateway-pdb
  namespace: dev-web
  labels:
    app.kubernetes.io/name: platform-gateway
    app.kubernetes.io/part-of: ai-base-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-gateway
