apiVersion: v1
kind: Secret
metadata:
  name: platform-gateway-secret
  namespace: dev-web
  labels:
    app.kubernetes.io/name: platform-gateway
    app.kubernetes.io/part-of: ai-base-app
type: Opaque
stringData:
  JWT_ACCESS_SECRET: "dev_access_secret_key_1234567890"
