apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-gateway-cm
  namespace: dev-web
  labels:
    app.kubernetes.io/name: platform-gateway
    app.kubernetes.io/part-of: ai-base-app
data:
  NODE_ENV: "development"
  PORT: "3000"
  AUTH_SERVICE_URL: "platform-auth-service.dev-api.svc.cluster.local:3001"
  CORE_SERVICE_URL: "platform-core-service.dev-api.svc.cluster.local:3005"
  JWT_ACCESS_SECRET: "dev_access_secret_key_1234567890"
  JWT_ACCESS_EXPIRES_IN: "3600"
  RABBITMQ_URL: "amqp://dev_rabbitmq_user:dev_rabbitmq_password@rabbitmq.dev-infra.svc.cluster.local:5672?frameMax=8192"
