apiVersion: v1
kind: Service
metadata:
  name: platform-core-service
  namespace: dev-service
  labels:
    app.kubernetes.io/name: platform-core-service
    app.kubernetes.io/part-of: ai-base-app
spec:
  ports:
  - name: http
    port: 3004
    targetPort: 3004
  - name: tcp
    port: 3005
    targetPort: 3005
  selector:
    app.kubernetes.io/name: platform-core-service
