apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespaces
  - ../../network-policies
  - ../../apps/service-gateway
  - ../../apps/platform-auth-service
  - ../../database/postgres
  - ../../database/redis
  - ../../messaging/rabbitmq
  - ../../messaging/kafka
  - ../../monitoring/loki
  - ../../monitoring/mimir
  - ../../monitoring/tempo
  - ../../monitoring/grafana
  - ../../monitoring/promtail
  - ../../networking

commonLabels:
  env: prod

patches:
  - target:
      kind: Deployment
      labelSelector: "app in (service-gateway, platform-auth-service)"
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  
  - target:
      kind: Deployment
      name: service-gateway
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
