apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps
  - ../../database
  - ../../messaging
  - ../../monitoring
  - ../../network-policies
  - ../../networking
  - monitoring-namespace.yaml
  - prod-api-namespace.yaml
  - prod-infra-namespace.yaml
  - prod-web-namespace.yaml
  - service-gateway-hpa.yaml
  - service-gateway-pdb.yaml
  - platform-auth-service-hpa.yaml
  - platform-auth-service-pdb.yaml
commonLabels:
  env: prod
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: postgres-secret
    envs:
      - secrets/postgres-secret.env
  - name: rabbitmq-secret
    envs:
      - secrets/rabbitmq-secret.env
    files:
      - default_user.conf=secrets/rabbitmq-default_user.conf
patches:
  - path: delete-postgres-secret.yaml
  - path: delete-rabbitmq-secret.yaml
  - target:
      kind: Deployment
      name: service-gateway-deploy
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-web
      - op: replace
        path: /spec/replicas
        value: 3
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      - op: add
        path: /spec/template/spec/topologySpreadConstraints
        value:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: service-gateway
                env: prod
      - op: add
        path: /spec/template/spec/affinity
        value:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: service-gateway
                      env: prod
  - target:
      kind: Deployment
      name: platform-auth-service-deploy
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-api
      - op: replace
        path: /spec/replicas
        value: 3
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      - op: add
        path: /spec/template/spec/topologySpreadConstraints
        value:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: platform-auth-service
                env: prod
      - op: add
        path: /spec/template/spec/affinity
        value:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: platform-auth-service
                      env: prod
  - target:
      kind: Service
      name: service-gateway
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-web
  - target:
      kind: Service
      name: platform-auth-service
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-api
  - target:
      kind: ConfigMap
      name: service-gateway-cm
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-web
      - op: replace
        path: /data/AUTH_SERVICE_HOST
        value: platform-auth-service.prod-api.svc.cluster.local
      - op: replace
        path: /data/AUTH_SERVICE_PORT
        value: "3001"
      - op: replace
        path: /data/NODE_ENV
        value: production
      - op: replace
        path: /data/RABBITMQ_URL
        value: amqp://rabbitmq.prod-infra.svc.cluster.local:5672
  - target:
      kind: ConfigMap
      name: platform-auth-service-cm
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-api
      - op: replace
        path: /data/NODE_ENV
        value: production
      - op: replace
        path: /data/RABBITMQ_URL
        value: amqp://prod_rabbitmq_user:CHANGE_ME_PROD_RABBITMQ_PASSWORD@rabbitmq.prod-infra.svc.cluster.local:5672
      - op: replace
        path: /data/DATABASE_URL
        value: postgres://prod_platform_user:CHANGE_ME_PROD_POSTGRES_PASSWORD@postgres-rw.prod-infra.svc.cluster.local:5432/platform_db
  - target:
      kind: Secret
      name: postgres-secret
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-infra
  - target:
      kind: Secret
      name: rabbitmq-secret
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-infra
  - target:
      kind: Gateway
      name: service-gateway-gw
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-web
  - target:
      kind: VirtualService
      name: service-gateway-vs
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-web
  - target:
      kind: Cluster
      name: postgres
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-infra
      - op: replace
        path: /spec/instances
        value: 3
      - op: replace
        path: /spec/storage/size
        value: 20Gi
  - target:
      kind: RedisCluster
      name: redis
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-infra
      - op: replace
        path: /spec/clusterSize
        value: 3
  - target:
      kind: Kafka
      name: kafka-cluster
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-infra
      - op: replace
        path: /spec/kafka/replicas
        value: 3
      - op: replace
        path: /spec/kafka/config/offsets.topic.replication.factor
        value: 3
      - op: replace
        path: /spec/kafka/config/transaction.state.log.replication.factor
        value: 3
      - op: replace
        path: /spec/kafka/config/transaction.state.log.min.isr
        value: 2
      - op: replace
        path: /spec/kafka/config/default.replication.factor
        value: 3
      - op: replace
        path: /spec/kafka/config/min.insync.replicas
        value: 2
  - target:
      kind: RabbitmqCluster
      name: rabbitmq
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-infra
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/persistence/storage
        value: 20Gi
      - op: add
        path: /spec/rabbitmq
        value:
          additionalConfig: |
            cluster_partition_handling = pause_minority
            vm_memory_high_watermark_paging_ratio = 0.99
      - op: add
        path: /spec/resources
        value:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
  - target:
      kind: NetworkPolicy
      name: egress-service-gateway-to-platform-auth
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-web
      - op: replace
        path: /spec/egress/0/to/0/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-api
  - target:
      kind: NetworkPolicy
      name: ingress-platform-auth-from-service-gateway
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-api
      - op: replace
        path: /spec/ingress/0/from/0/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-web
  - target:
      kind: NetworkPolicy
      name: egress-platform-auth-to-kafka
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-api
      - op: replace
        path: /spec/egress/0/to/0/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-infra
  - target:
      kind: NetworkPolicy
      name: egress-platform-auth-to-postgres
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-api
      - op: replace
        path: /spec/egress/0/to/0/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-infra
  - target:
      kind: NetworkPolicy
      name: egress-platform-auth-to-rabbitmq
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-api
      - op: replace
        path: /spec/egress/0/to/0/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-infra
  - target:
      kind: NetworkPolicy
      name: egress-platform-auth-to-redis
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-api
      - op: replace
        path: /spec/egress/0/to/0/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-infra
  - target:
      kind: NetworkPolicy
      name: egress-service-gateway-to-kafka
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-web
      - op: replace
        path: /spec/egress/0/to/0/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-infra
  - target:
      kind: NetworkPolicy
      name: egress-service-gateway-to-postgres
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-web
      - op: replace
        path: /spec/egress/0/to/0/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-infra
  - target:
      kind: NetworkPolicy
      name: egress-service-gateway-to-rabbitmq
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-web
      - op: replace
        path: /spec/egress/0/to/0/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-infra
  - target:
      kind: NetworkPolicy
      name: egress-service-gateway-to-redis
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-web
      - op: replace
        path: /spec/egress/0/to/0/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-infra
  - target:
      kind: NetworkPolicy
      name: ingress-kafka-from-apps
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-infra
      - op: replace
        path: /spec/ingress/0/from/0/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-api
      - op: replace
        path: /spec/ingress/0/from/1/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-web
  - target:
      kind: NetworkPolicy
      name: ingress-postgres-from-apps
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-infra
      - op: replace
        path: /spec/ingress/0/from/0/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-api
      - op: replace
        path: /spec/ingress/0/from/1/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-web
  - target:
      kind: NetworkPolicy
      name: ingress-rabbitmq-from-apps
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-infra
      - op: replace
        path: /spec/ingress/0/from/0/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-api
      - op: replace
        path: /spec/ingress/0/from/1/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-web
  - target:
      kind: NetworkPolicy
      name: ingress-redis-from-apps
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-infra
      - op: replace
        path: /spec/ingress/0/from/0/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-api
      - op: replace
        path: /spec/ingress/0/from/1/namespaceSelector/matchLabels/kubernetes.io~1metadata.name
        value: prod-web
  - target:
      kind: NetworkPolicy
      name: ingress-service-gateway-from-istio-ingress
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-web
  - target:
      kind: NetworkPolicy
      name: default-deny-all
      namespace: dev-api
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-api
  - target:
      kind: NetworkPolicy
      name: default-deny-all
      namespace: dev-infra
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-infra
  - target:
      kind: NetworkPolicy
      name: default-deny-all
      namespace: dev-web
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-web
  - target:
      kind: NetworkPolicy
      name: egress-api-to-dns
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-api
  - target:
      kind: NetworkPolicy
      name: egress-infra-to-dns
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-infra
  - target:
      kind: NetworkPolicy
      name: egress-web-to-dns
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-web
  - target:
      kind: KafkaNodePool
      name: dual-role
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-infra
      - op: replace
        path: /spec/storage/volumes/0/size
        value: 20Gi
  - target:
      kind: StatefulSet
      name: loki-sts
    patch: |-
      - op: remove
        path: /spec/template/spec/volumes/2
      - op: add
        path: /spec/volumeClaimTemplates
        value:
          - metadata:
              name: data
            spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 10Gi
  - target:
      kind: StatefulSet
      name: tempo-sts
    patch: |-
      - op: remove
        path: /spec/template/spec/volumes/2
      - op: add
        path: /spec/volumeClaimTemplates
        value:
          - metadata:
              name: data
            spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 10Gi
  - target:
      kind: StatefulSet
      name: mimir-sts
    patch: |-
      - op: remove
        path: /spec/template/spec/volumes/2
      - op: add
        path: /spec/volumeClaimTemplates
        value:
          - metadata:
              name: data
            spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 10Gi
  - target:
      kind: StatefulSet
      name: grafana-sts
    patch: |-
      - op: remove
        path: /spec/template/spec/volumes/1
      - op: add
        path: /spec/volumeClaimTemplates
        value:
          - metadata:
              name: data
            spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: 5Gi
