apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: platform-auth-service-pdb
  namespace: prod-api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-auth-service
