apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: platform-gateway-pdb
  namespace: prod-web
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-gateway
