apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: platform-core-service-hpa
  namespace: prod-service
  labels:
    app.kubernetes.io/name: platform-core-service
    app.kubernetes.io/part-of: ai-base-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: platform-core-service-deploy
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
