apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress-service-gateway-from-istio-ingress.yaml
  - egress-service-gateway-to-platform-auth.yaml
  - ingress-platform-auth-from-service-gateway.yaml
