apiVersion: v1
kind: Service
metadata:
  name: platform-auth-service
  namespace: dev-api
spec:
  selector:
    app: platform-auth-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
