apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: platform-auth-service-pdb
  namespace: dev-api
  labels:
    app.kubernetes.io/name: platform-auth-service
    app.kubernetes.io/part-of: ai-base-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-auth-service
