apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-auth-service-cm
  namespace: dev-api
  labels:
    app.kubernetes.io/name: platform-auth-service
    app.kubernetes.io/part-of: ai-base-app
data:
  NODE_ENV: "development"
  PORT: "3000"
  TCP_PORT: "3001"
  DATABASE_URL: "postgres://platform_user:postgrespassword@postgres-rw.dev-infra.svc.cluster.local:5432/platform_db"
  REDIS_URL: "redis://:dev_redis_password@redis-leader.dev-infra.svc.cluster.local:6379"
  JWT_ACCESS_SECRET: "dev_access_secret_key_1234567890"
  JWT_REFRESH_SECRET: "dev_refresh_secret_key_1234567890"
  JWT_ACCESS_EXPIRES_IN: "3600"
  JWT_REFRESH_EXPIRES_IN: "604800"
