apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-auth-service-cm
  namespace: dev-api
  labels:
    app.kubernetes.io/name: platform-auth-service
    app.kubernetes.io/part-of: ai-base-app
data:
  RABBITMQ_URL: "amqp://dev_rabbitmq_user:dev_rabbitmq_password@rabbitmq.dev-infra.svc.cluster.local:5672?frameMax=8192"
  DATABASE_URL: "postgres://platform_user:postgrespassword@postgres-rw.dev-infra.svc.cluster.local:5432/platform_db"
  NODE_ENV: "development"
