apiVersion: v1
kind: Secret
metadata:
  name: platform-auth-service-secret
  namespace: dev-service
  labels:
    app.kubernetes.io/name: platform-auth-service
    app.kubernetes.io/part-of: ai-base-app
type: Opaque
stringData:
  DATABASE_URL: "postgresql://platform_user:postgrespassword@postgres-rw.dev-infra.svc.cluster.local:5432/platform_db"
  REDIS_URL: "redis://:dev_redis_password@redis-leader.dev-infra.svc.cluster.local:6379"
  JWT_ACCESS_SECRET: "dev_access_secret_key_1234567890"
  JWT_REFRESH_SECRET: "dev_refresh_secret_key_1234567890"
