apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - egress-web-to-dns.yaml
  - egress-api-to-dns.yaml
  - egress-infra-to-dns.yaml
  - egress-monitoring-to-dns.yaml
  - egress-monitoring-to-monitoring.yaml
  - egress-monitoring-to-kube-system-https.yaml
  - ingress-monitoring-from-monitoring.yaml
