apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy-ds
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alloy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alloy
    spec:
      serviceAccountName: alloy
      containers:
      - name: alloy
        image: grafana/alloy:v1.15.1
        imagePullPolicy: IfNotPresent
        args:
        - run
        - --storage.path=/tmp/alloy
        - /etc/alloy/config.alloy
        volumeMounts:
        - name: logs
          mountPath: /var/log/pods
          readOnly: true
        - name: config
          mountPath: /etc/alloy
        ports:
        - containerPort: 12345
          name: http-metrics
      volumes:
      - name: logs
        hostPath:
          path: /var/log/pods
      - name: config
        configMap:
          name: alloy-cm
