apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespaces
  - ../../network-policies
  - ../../apps/service-gateway
  - ../../apps/platform-auth-service
  - ../../database/postgres
  - ../../database/redis
  - ../../messaging/rabbitmq
  - ../../messaging/kafka
  - ../../monitoring/loki
  - ../../monitoring/mimir
  - ../../monitoring/tempo
  - ../../monitoring/grafana
  - ../../monitoring/promtail
  - ../../networking

commonLabels:
  env: dev

# [개발 환경 다이어트] 모든 복제본을 1개로 축소
patches:
  # 1. 일반 앱 (Deployment)
  - target:
      kind: Deployment
      labelSelector: "app in (service-gateway, platform-auth-service)"
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  # 2. Postgres (CloudNativePG Cluster)
  - target:
      kind: Cluster
      name: postgres
    patch: |-
      - op: replace
        path: /spec/instances
        value: 1

  # 3. RabbitMQ (RabbitmqCluster)
  - target:
      kind: RabbitmqCluster
      name: rabbitmq
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  # 4. Redis (Redis Operator)
  - target:
      kind: Redis
      name: redis
    patch: |-
      - op: replace
        path: /spec/size
        value: 1

  # 5. Kafka (Strimzi)
  - target:
      kind: Kafka
      name: kafka
    patch: |-
      - op: replace
        path: /spec/kafka/replicas
        value: 1
