apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. 공통 리소스 정의
resources:
  - ../../namespaces
  - ../../apps
  - ../../database
  - ../../messaging
  - ../../networking

# 2. 공통 라벨 주입
labels:
  - pairs:
      env: dev
