apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-cm
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Mimir
      type: prometheus
      url: http://mimir.monitoring.svc.cluster.local:8080/prometheus
      access: proxy
      isDefault: true
      editable: true
    - name: Loki
      type: loki
      url: http://loki.monitoring.svc.cluster.local:3100
      access: proxy
      editable: true
    - name: Tempo
      type: tempo
      url: http://tempo.monitoring.svc.cluster.local:3200
      access: proxy
      editable: true
      jsonData:
        lokiSearch:
          datasourceUid: 'Loki'
        tracesToLogs:
          datasourceUid: 'Loki'
          filterByTraceId: true
