apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-sts.yaml
  - grafana-svc.yaml
  - grafana-datasources-cm.yaml
  - grafana-provisioning-cm.yaml
  - grafana-dashboard-cm.yaml
