apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - default-deny-all-dev-web.yaml
  - default-deny-all-dev-api.yaml
  - default-deny-all-dev-infra.yaml
  - default-deny-all-monitoring.yaml
