/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponse,
  AuthControllerGetMeV1200,
  AuthControllerLoginV1200,
  AuthControllerPermissionsV1200,
  AuthControllerRefreshV1200,
  ChangePasswordDto,
  HealthControllerLive200,
  HealthControllerLive503,
  HealthControllerReady200,
  HealthControllerReady503,
  LoginDto
} from './model';

import authControllerLoginV1Mutator from '../lib/axios';
import type { ErrorType as AuthControllerLoginV1ErrorType } from '../lib/axios';
import authControllerPermissionsV1Mutator from '../lib/axios';
import type { ErrorType as AuthControllerPermissionsV1ErrorType } from '../lib/axios';
import authControllerRefreshV1Mutator from '../lib/axios';
import type { ErrorType as AuthControllerRefreshV1ErrorType } from '../lib/axios';
import authControllerGetMeV1Mutator from '../lib/axios';
import type { ErrorType as AuthControllerGetMeV1ErrorType } from '../lib/axios';
import authControllerLogoutV1Mutator from '../lib/axios';
import type { ErrorType as AuthControllerLogoutV1ErrorType } from '../lib/axios';
import authControllerDeferPasswordChangeV1Mutator from '../lib/axios';
import type { ErrorType as AuthControllerDeferPasswordChangeV1ErrorType } from '../lib/axios';
import authControllerChangePasswordV1Mutator from '../lib/axios';
import type { ErrorType as AuthControllerChangePasswordV1ErrorType } from '../lib/axios';
import healthControllerLiveMutator from '../lib/axios';
import type { ErrorType as HealthControllerLiveErrorType } from '../lib/axios';
import healthControllerReadyMutator from '../lib/axios';
import type { ErrorType as HealthControllerReadyErrorType } from '../lib/axios';




/**
 * 인증 서비스로 로그인 요청을 전달하고 Refresh Token을 쿠키에 설정합니다.
 * @summary 로그인
 */
export const authControllerLoginV1 = (
    loginDto: LoginDto,
 signal?: AbortSignal
) => {


      return authControllerLoginV1Mutator<AuthControllerLoginV1200>(
      {url: `/api/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginDto, signal
    },
      );
    }



export const getAuthControllerLoginV1MutationOptions = <TError = AuthControllerLoginV1ErrorType<ApiResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginV1>>, TError,{data: LoginDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginV1>>, TError,{data: LoginDto}, TContext> => {

const mutationKey = ['authControllerLoginV1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLoginV1>>, {data: LoginDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerLoginV1(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLoginV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLoginV1>>>
    export type AuthControllerLoginV1MutationBody = LoginDto
    export type AuthControllerLoginV1MutationError = AuthControllerLoginV1ErrorType<ApiResponse>

    /**
 * @summary 로그인
 */
export const useAuthControllerLoginV1 = <TError = AuthControllerLoginV1ErrorType<ApiResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginV1>>, TError,{data: LoginDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLoginV1>>,
        TError,
        {data: LoginDto},
        TContext
      > => {
      return useMutation(getAuthControllerLoginV1MutationOptions(options), queryClient);
    }

/**
 * 현재 인증된 관리자 계정과 테넌트 기준으로 역할과 권한 목록을 반환합니다.
 * @summary 권한 조회
 */
export const authControllerPermissionsV1 = (

 signal?: AbortSignal
) => {


      return authControllerPermissionsV1Mutator<AuthControllerPermissionsV1200>(
      {url: `/api/v1/auth/permissions`, method: 'GET', signal
    },
      );
    }




export const getAuthControllerPermissionsV1QueryKey = () => {
    return [
    `/api/v1/auth/permissions`
    ] as const;
    }


export const getAuthControllerPermissionsV1QueryOptions = <TData = Awaited<ReturnType<typeof authControllerPermissionsV1>>, TError = AuthControllerPermissionsV1ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerPermissionsV1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerPermissionsV1QueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerPermissionsV1>>> = ({ signal }) => authControllerPermissionsV1(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerPermissionsV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerPermissionsV1QueryResult = NonNullable<Awaited<ReturnType<typeof authControllerPermissionsV1>>>
export type AuthControllerPermissionsV1QueryError = AuthControllerPermissionsV1ErrorType<unknown>


export function useAuthControllerPermissionsV1<TData = Awaited<ReturnType<typeof authControllerPermissionsV1>>, TError = AuthControllerPermissionsV1ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerPermissionsV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerPermissionsV1>>,
          TError,
          Awaited<ReturnType<typeof authControllerPermissionsV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerPermissionsV1<TData = Awaited<ReturnType<typeof authControllerPermissionsV1>>, TError = AuthControllerPermissionsV1ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerPermissionsV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerPermissionsV1>>,
          TError,
          Awaited<ReturnType<typeof authControllerPermissionsV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerPermissionsV1<TData = Awaited<ReturnType<typeof authControllerPermissionsV1>>, TError = AuthControllerPermissionsV1ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerPermissionsV1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 권한 조회
 */

export function useAuthControllerPermissionsV1<TData = Awaited<ReturnType<typeof authControllerPermissionsV1>>, TError = AuthControllerPermissionsV1ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerPermissionsV1>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerPermissionsV1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * 쿠키의 리프레시 토큰을 사용하여 액세스 토큰을 갱신합니다.
 * @summary 토큰 갱신
 */
export const authControllerRefreshV1 = (

 signal?: AbortSignal
) => {


      return authControllerRefreshV1Mutator<AuthControllerRefreshV1200>(
      {url: `/api/v1/auth/refresh`, method: 'POST', signal
    },
      );
    }



export const getAuthControllerRefreshV1MutationOptions = <TError = AuthControllerRefreshV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRefreshV1>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerRefreshV1>>, TError,void, TContext> => {

const mutationKey = ['authControllerRefreshV1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRefreshV1>>, void> = () => {


          return  authControllerRefreshV1()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerRefreshV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRefreshV1>>>

    export type AuthControllerRefreshV1MutationError = AuthControllerRefreshV1ErrorType<unknown>

    /**
 * @summary 토큰 갱신
 */
export const useAuthControllerRefreshV1 = <TError = AuthControllerRefreshV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRefreshV1>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerRefreshV1>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerRefreshV1MutationOptions(options), queryClient);
    }

/**
 * JWT 토큰을 통해 인증된 현재 관리자 계정의 정보를 반환합니다.
 * @summary 내 정보 조회
 */
export const authControllerGetMeV1 = (

 signal?: AbortSignal
) => {


      return authControllerGetMeV1Mutator<AuthControllerGetMeV1200>(
      {url: `/api/v1/auth/me`, method: 'GET', signal
    },
      );
    }




export const getAuthControllerGetMeV1QueryKey = () => {
    return [
    `/api/v1/auth/me`
    ] as const;
    }


export const getAuthControllerGetMeV1QueryOptions = <TData = Awaited<ReturnType<typeof authControllerGetMeV1>>, TError = AuthControllerGetMeV1ErrorType<ApiResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMeV1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerGetMeV1QueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGetMeV1>>> = ({ signal }) => authControllerGetMeV1(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMeV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerGetMeV1QueryResult = NonNullable<Awaited<ReturnType<typeof authControllerGetMeV1>>>
export type AuthControllerGetMeV1QueryError = AuthControllerGetMeV1ErrorType<ApiResponse>


export function useAuthControllerGetMeV1<TData = Awaited<ReturnType<typeof authControllerGetMeV1>>, TError = AuthControllerGetMeV1ErrorType<ApiResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMeV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetMeV1>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetMeV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerGetMeV1<TData = Awaited<ReturnType<typeof authControllerGetMeV1>>, TError = AuthControllerGetMeV1ErrorType<ApiResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMeV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetMeV1>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetMeV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerGetMeV1<TData = Awaited<ReturnType<typeof authControllerGetMeV1>>, TError = AuthControllerGetMeV1ErrorType<ApiResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMeV1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내 정보 조회
 */

export function useAuthControllerGetMeV1<TData = Awaited<ReturnType<typeof authControllerGetMeV1>>, TError = AuthControllerGetMeV1ErrorType<ApiResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMeV1>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerGetMeV1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * 세션을 종료하고 리프레시 토큰 쿠키를 제거합니다.
 * @summary 로그아웃
 */
export const authControllerLogoutV1 = (

 signal?: AbortSignal
) => {


      return authControllerLogoutV1Mutator<ApiResponse>(
      {url: `/api/v1/auth/logout`, method: 'POST', signal
    },
      );
    }



export const getAuthControllerLogoutV1MutationOptions = <TError = AuthControllerLogoutV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogoutV1>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogoutV1>>, TError,void, TContext> => {

const mutationKey = ['authControllerLogoutV1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogoutV1>>, void> = () => {


          return  authControllerLogoutV1()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLogoutV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogoutV1>>>

    export type AuthControllerLogoutV1MutationError = AuthControllerLogoutV1ErrorType<unknown>

    /**
 * @summary 로그아웃
 */
export const useAuthControllerLogoutV1 = <TError = AuthControllerLogoutV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogoutV1>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogoutV1>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerLogoutV1MutationOptions(options), queryClient);
    }

/**
 * 비밀번호 변경 안내를 확인하고 90일 연장합니다.
 * @summary 비밀번호 변경 연장
 */
export const authControllerDeferPasswordChangeV1 = (

 signal?: AbortSignal
) => {


      return authControllerDeferPasswordChangeV1Mutator<ApiResponse>(
      {url: `/api/v1/auth/password/defer`, method: 'POST', signal
    },
      );
    }



export const getAuthControllerDeferPasswordChangeV1MutationOptions = <TError = AuthControllerDeferPasswordChangeV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerDeferPasswordChangeV1>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerDeferPasswordChangeV1>>, TError,void, TContext> => {

const mutationKey = ['authControllerDeferPasswordChangeV1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerDeferPasswordChangeV1>>, void> = () => {


          return  authControllerDeferPasswordChangeV1()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerDeferPasswordChangeV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerDeferPasswordChangeV1>>>

    export type AuthControllerDeferPasswordChangeV1MutationError = AuthControllerDeferPasswordChangeV1ErrorType<unknown>

    /**
 * @summary 비밀번호 변경 연장
 */
export const useAuthControllerDeferPasswordChangeV1 = <TError = AuthControllerDeferPasswordChangeV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerDeferPasswordChangeV1>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerDeferPasswordChangeV1>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerDeferPasswordChangeV1MutationOptions(options), queryClient);
    }

/**
 * 현재 비밀번호를 확인하고 새로운 비밀번호로 변경합니다.
 * @summary 비밀번호 변경
 */
export const authControllerChangePasswordV1 = (
    changePasswordDto: ChangePasswordDto,
 signal?: AbortSignal
) => {


      return authControllerChangePasswordV1Mutator<ApiResponse>(
      {url: `/api/v1/auth/password/change`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordDto, signal
    },
      );
    }



export const getAuthControllerChangePasswordV1MutationOptions = <TError = AuthControllerChangePasswordV1ErrorType<ApiResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerChangePasswordV1>>, TError,{data: ChangePasswordDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerChangePasswordV1>>, TError,{data: ChangePasswordDto}, TContext> => {

const mutationKey = ['authControllerChangePasswordV1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerChangePasswordV1>>, {data: ChangePasswordDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerChangePasswordV1(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerChangePasswordV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerChangePasswordV1>>>
    export type AuthControllerChangePasswordV1MutationBody = ChangePasswordDto
    export type AuthControllerChangePasswordV1MutationError = AuthControllerChangePasswordV1ErrorType<ApiResponse>

    /**
 * @summary 비밀번호 변경
 */
export const useAuthControllerChangePasswordV1 = <TError = AuthControllerChangePasswordV1ErrorType<ApiResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerChangePasswordV1>>, TError,{data: ChangePasswordDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerChangePasswordV1>>,
        TError,
        {data: ChangePasswordDto},
        TContext
      > => {
      return useMutation(getAuthControllerChangePasswordV1MutationOptions(options), queryClient);
    }

export const healthControllerLive = (

 signal?: AbortSignal
) => {


      return healthControllerLiveMutator<HealthControllerLive200>(
      {url: `/health/live`, method: 'GET', signal
    },
      );
    }




export const getHealthControllerLiveQueryKey = () => {
    return [
    `/health/live`
    ] as const;
    }


export const getHealthControllerLiveQueryOptions = <TData = Awaited<ReturnType<typeof healthControllerLive>>, TError = HealthControllerLiveErrorType<HealthControllerLive503>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerLive>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthControllerLiveQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthControllerLive>>> = ({ signal }) => healthControllerLive(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthControllerLive>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthControllerLiveQueryResult = NonNullable<Awaited<ReturnType<typeof healthControllerLive>>>
export type HealthControllerLiveQueryError = HealthControllerLiveErrorType<HealthControllerLive503>


export function useHealthControllerLive<TData = Awaited<ReturnType<typeof healthControllerLive>>, TError = HealthControllerLiveErrorType<HealthControllerLive503>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerLive>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerLive>>,
          TError,
          Awaited<ReturnType<typeof healthControllerLive>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthControllerLive<TData = Awaited<ReturnType<typeof healthControllerLive>>, TError = HealthControllerLiveErrorType<HealthControllerLive503>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerLive>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerLive>>,
          TError,
          Awaited<ReturnType<typeof healthControllerLive>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthControllerLive<TData = Awaited<ReturnType<typeof healthControllerLive>>, TError = HealthControllerLiveErrorType<HealthControllerLive503>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerLive>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useHealthControllerLive<TData = Awaited<ReturnType<typeof healthControllerLive>>, TError = HealthControllerLiveErrorType<HealthControllerLive503>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerLive>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthControllerLiveQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const healthControllerReady = (

 signal?: AbortSignal
) => {


      return healthControllerReadyMutator<HealthControllerReady200>(
      {url: `/health/ready`, method: 'GET', signal
    },
      );
    }




export const getHealthControllerReadyQueryKey = () => {
    return [
    `/health/ready`
    ] as const;
    }


export const getHealthControllerReadyQueryOptions = <TData = Awaited<ReturnType<typeof healthControllerReady>>, TError = HealthControllerReadyErrorType<HealthControllerReady503>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerReady>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthControllerReadyQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthControllerReady>>> = ({ signal }) => healthControllerReady(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthControllerReady>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthControllerReadyQueryResult = NonNullable<Awaited<ReturnType<typeof healthControllerReady>>>
export type HealthControllerReadyQueryError = HealthControllerReadyErrorType<HealthControllerReady503>


export function useHealthControllerReady<TData = Awaited<ReturnType<typeof healthControllerReady>>, TError = HealthControllerReadyErrorType<HealthControllerReady503>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerReady>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerReady>>,
          TError,
          Awaited<ReturnType<typeof healthControllerReady>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthControllerReady<TData = Awaited<ReturnType<typeof healthControllerReady>>, TError = HealthControllerReadyErrorType<HealthControllerReady503>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerReady>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerReady>>,
          TError,
          Awaited<ReturnType<typeof healthControllerReady>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthControllerReady<TData = Awaited<ReturnType<typeof healthControllerReady>>, TError = HealthControllerReadyErrorType<HealthControllerReady503>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerReady>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useHealthControllerReady<TData = Awaited<ReturnType<typeof healthControllerReady>>, TError = HealthControllerReadyErrorType<HealthControllerReady503>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerReady>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthControllerReadyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







