/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App API
 * The AI Base App Gateway API documentation
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AgreeTermsDto,
  ApiResponse,
  AuthControllerGetMeV1200,
  AuthControllerLoginV1200,
  AuthControllerRefreshV1200,
  ChangePasswordDto,
  CoreControllerAgreeTermsV1200,
  CoreControllerCreateAnnouncementV1200,
  CoreControllerCreateTermsDocumentV1200,
  CoreControllerCreateTermsVersionV1200,
  CoreControllerGetActiveTermsV1200,
  CoreControllerGetActiveTermsV1Params,
  CoreControllerGetAnnouncementsV1200,
  CoreControllerGetAnnouncementsV1Params,
  CoreControllerGetOrganizationsV1200,
  CoreControllerGetOrganizationsV1Params,
  CoreControllerGetTicketsV1200,
  CoreControllerGetTicketsV1Params,
  CreateAnnouncementDto,
  CreateTermsDocumentDto,
  CreateTermsVersionDto,
  HealthControllerLive200,
  HealthControllerLive503,
  HealthControllerReady200,
  HealthControllerReady503,
  LoginDto
} from './model';

import authControllerLoginV1Mutator from '../lib/axios';
import type { ErrorType as AuthControllerLoginV1ErrorType } from '../lib/axios';
import authControllerRefreshV1Mutator from '../lib/axios';
import type { ErrorType as AuthControllerRefreshV1ErrorType } from '../lib/axios';
import authControllerGetMeV1Mutator from '../lib/axios';
import type { ErrorType as AuthControllerGetMeV1ErrorType } from '../lib/axios';
import authControllerLogoutV1Mutator from '../lib/axios';
import type { ErrorType as AuthControllerLogoutV1ErrorType } from '../lib/axios';
import authControllerDeferPasswordChangeV1Mutator from '../lib/axios';
import type { ErrorType as AuthControllerDeferPasswordChangeV1ErrorType } from '../lib/axios';
import authControllerChangePasswordV1Mutator from '../lib/axios';
import type { ErrorType as AuthControllerChangePasswordV1ErrorType } from '../lib/axios';
import coreControllerGetOrganizationsV1Mutator from '../lib/axios';
import type { ErrorType as CoreControllerGetOrganizationsV1ErrorType } from '../lib/axios';
import coreControllerApproveOrganizationV1Mutator from '../lib/axios';
import type { ErrorType as CoreControllerApproveOrganizationV1ErrorType } from '../lib/axios';
import coreControllerRejectOrganizationV1Mutator from '../lib/axios';
import type { ErrorType as CoreControllerRejectOrganizationV1ErrorType } from '../lib/axios';
import coreControllerGetAnnouncementsV1Mutator from '../lib/axios';
import type { ErrorType as CoreControllerGetAnnouncementsV1ErrorType } from '../lib/axios';
import coreControllerCreateAnnouncementV1Mutator from '../lib/axios';
import type { ErrorType as CoreControllerCreateAnnouncementV1ErrorType } from '../lib/axios';
import coreControllerGetTicketsV1Mutator from '../lib/axios';
import type { ErrorType as CoreControllerGetTicketsV1ErrorType } from '../lib/axios';
import coreControllerGetActiveTermsV1Mutator from '../lib/axios';
import type { ErrorType as CoreControllerGetActiveTermsV1ErrorType } from '../lib/axios';
import coreControllerCreateTermsDocumentV1Mutator from '../lib/axios';
import type { ErrorType as CoreControllerCreateTermsDocumentV1ErrorType } from '../lib/axios';
import coreControllerCreateTermsVersionV1Mutator from '../lib/axios';
import type { ErrorType as CoreControllerCreateTermsVersionV1ErrorType } from '../lib/axios';
import coreControllerAgreeTermsV1Mutator from '../lib/axios';
import type { ErrorType as CoreControllerAgreeTermsV1ErrorType } from '../lib/axios';
import healthControllerLiveMutator from '../lib/axios';
import type { ErrorType as HealthControllerLiveErrorType } from '../lib/axios';
import healthControllerReadyMutator from '../lib/axios';
import type { ErrorType as HealthControllerReadyErrorType } from '../lib/axios';




/**
 * 인증 서비스로 로그인 요청을 전달하고 Refresh Token을 쿠키에 설정합니다.
 * @summary 로그인
 */
export const authControllerLoginV1 = (
    loginDto: LoginDto,
 signal?: AbortSignal
) => {


      return authControllerLoginV1Mutator<AuthControllerLoginV1200>(
      {url: `/api/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginDto, signal
    },
      );
    }



export const getAuthControllerLoginV1MutationOptions = <TError = AuthControllerLoginV1ErrorType<ApiResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginV1>>, TError,{data: LoginDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginV1>>, TError,{data: LoginDto}, TContext> => {

const mutationKey = ['authControllerLoginV1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLoginV1>>, {data: LoginDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerLoginV1(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLoginV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLoginV1>>>
    export type AuthControllerLoginV1MutationBody = LoginDto
    export type AuthControllerLoginV1MutationError = AuthControllerLoginV1ErrorType<ApiResponse>

    /**
 * @summary 로그인
 */
export const useAuthControllerLoginV1 = <TError = AuthControllerLoginV1ErrorType<ApiResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLoginV1>>, TError,{data: LoginDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLoginV1>>,
        TError,
        {data: LoginDto},
        TContext
      > => {
      return useMutation(getAuthControllerLoginV1MutationOptions(options), queryClient);
    }

/**
 * 쿠키의 리프레시 토큰을 사용하여 액세스 토큰을 갱신합니다.
 * @summary 토큰 갱신
 */
export const authControllerRefreshV1 = (

 signal?: AbortSignal
) => {


      return authControllerRefreshV1Mutator<AuthControllerRefreshV1200>(
      {url: `/api/v1/auth/refresh`, method: 'POST', signal
    },
      );
    }



export const getAuthControllerRefreshV1MutationOptions = <TError = AuthControllerRefreshV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRefreshV1>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerRefreshV1>>, TError,void, TContext> => {

const mutationKey = ['authControllerRefreshV1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRefreshV1>>, void> = () => {


          return  authControllerRefreshV1()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerRefreshV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRefreshV1>>>

    export type AuthControllerRefreshV1MutationError = AuthControllerRefreshV1ErrorType<unknown>

    /**
 * @summary 토큰 갱신
 */
export const useAuthControllerRefreshV1 = <TError = AuthControllerRefreshV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRefreshV1>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerRefreshV1>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerRefreshV1MutationOptions(options), queryClient);
    }

/**
 * JWT 토큰을 통해 인증된 현재 관리자 계정의 정보를 반환합니다.
 * @summary 내 정보 조회
 */
export const authControllerGetMeV1 = (

 signal?: AbortSignal
) => {


      return authControllerGetMeV1Mutator<AuthControllerGetMeV1200>(
      {url: `/api/v1/auth/me`, method: 'GET', signal
    },
      );
    }




export const getAuthControllerGetMeV1QueryKey = () => {
    return [
    `/api/v1/auth/me`
    ] as const;
    }


export const getAuthControllerGetMeV1QueryOptions = <TData = Awaited<ReturnType<typeof authControllerGetMeV1>>, TError = AuthControllerGetMeV1ErrorType<ApiResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMeV1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerGetMeV1QueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGetMeV1>>> = ({ signal }) => authControllerGetMeV1(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMeV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthControllerGetMeV1QueryResult = NonNullable<Awaited<ReturnType<typeof authControllerGetMeV1>>>
export type AuthControllerGetMeV1QueryError = AuthControllerGetMeV1ErrorType<ApiResponse>


export function useAuthControllerGetMeV1<TData = Awaited<ReturnType<typeof authControllerGetMeV1>>, TError = AuthControllerGetMeV1ErrorType<ApiResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMeV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetMeV1>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetMeV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerGetMeV1<TData = Awaited<ReturnType<typeof authControllerGetMeV1>>, TError = AuthControllerGetMeV1ErrorType<ApiResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMeV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetMeV1>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetMeV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthControllerGetMeV1<TData = Awaited<ReturnType<typeof authControllerGetMeV1>>, TError = AuthControllerGetMeV1ErrorType<ApiResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMeV1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 내 정보 조회
 */

export function useAuthControllerGetMeV1<TData = Awaited<ReturnType<typeof authControllerGetMeV1>>, TError = AuthControllerGetMeV1ErrorType<ApiResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMeV1>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthControllerGetMeV1QueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * 세션을 종료하고 리프레시 토큰 쿠키를 제거합니다.
 * @summary 로그아웃
 */
export const authControllerLogoutV1 = (

 signal?: AbortSignal
) => {


      return authControllerLogoutV1Mutator<ApiResponse>(
      {url: `/api/v1/auth/logout`, method: 'POST', signal
    },
      );
    }



export const getAuthControllerLogoutV1MutationOptions = <TError = AuthControllerLogoutV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogoutV1>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogoutV1>>, TError,void, TContext> => {

const mutationKey = ['authControllerLogoutV1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogoutV1>>, void> = () => {


          return  authControllerLogoutV1()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLogoutV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogoutV1>>>

    export type AuthControllerLogoutV1MutationError = AuthControllerLogoutV1ErrorType<unknown>

    /**
 * @summary 로그아웃
 */
export const useAuthControllerLogoutV1 = <TError = AuthControllerLogoutV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogoutV1>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogoutV1>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerLogoutV1MutationOptions(options), queryClient);
    }

/**
 * 비밀번호 변경 안내를 확인하고 90일 연장합니다.
 * @summary 비밀번호 변경 연장
 */
export const authControllerDeferPasswordChangeV1 = (

 signal?: AbortSignal
) => {


      return authControllerDeferPasswordChangeV1Mutator<ApiResponse>(
      {url: `/api/v1/auth/password/defer`, method: 'POST', signal
    },
      );
    }



export const getAuthControllerDeferPasswordChangeV1MutationOptions = <TError = AuthControllerDeferPasswordChangeV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerDeferPasswordChangeV1>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerDeferPasswordChangeV1>>, TError,void, TContext> => {

const mutationKey = ['authControllerDeferPasswordChangeV1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerDeferPasswordChangeV1>>, void> = () => {


          return  authControllerDeferPasswordChangeV1()
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerDeferPasswordChangeV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerDeferPasswordChangeV1>>>

    export type AuthControllerDeferPasswordChangeV1MutationError = AuthControllerDeferPasswordChangeV1ErrorType<unknown>

    /**
 * @summary 비밀번호 변경 연장
 */
export const useAuthControllerDeferPasswordChangeV1 = <TError = AuthControllerDeferPasswordChangeV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerDeferPasswordChangeV1>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerDeferPasswordChangeV1>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerDeferPasswordChangeV1MutationOptions(options), queryClient);
    }

/**
 * 현재 비밀번호를 확인하고 새로운 비밀번호로 변경합니다.
 * @summary 비밀번호 변경
 */
export const authControllerChangePasswordV1 = (
    changePasswordDto: ChangePasswordDto,
 signal?: AbortSignal
) => {


      return authControllerChangePasswordV1Mutator<ApiResponse>(
      {url: `/api/v1/auth/password/change`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changePasswordDto, signal
    },
      );
    }



export const getAuthControllerChangePasswordV1MutationOptions = <TError = AuthControllerChangePasswordV1ErrorType<ApiResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerChangePasswordV1>>, TError,{data: ChangePasswordDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof authControllerChangePasswordV1>>, TError,{data: ChangePasswordDto}, TContext> => {

const mutationKey = ['authControllerChangePasswordV1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerChangePasswordV1>>, {data: ChangePasswordDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerChangePasswordV1(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerChangePasswordV1MutationResult = NonNullable<Awaited<ReturnType<typeof authControllerChangePasswordV1>>>
    export type AuthControllerChangePasswordV1MutationBody = ChangePasswordDto
    export type AuthControllerChangePasswordV1MutationError = AuthControllerChangePasswordV1ErrorType<ApiResponse>

    /**
 * @summary 비밀번호 변경
 */
export const useAuthControllerChangePasswordV1 = <TError = AuthControllerChangePasswordV1ErrorType<ApiResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerChangePasswordV1>>, TError,{data: ChangePasswordDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerChangePasswordV1>>,
        TError,
        {data: ChangePasswordDto},
        TContext
      > => {
      return useMutation(getAuthControllerChangePasswordV1MutationOptions(options), queryClient);
    }

/**
 * 플랫폼의 모든 조직 목록을 조회합니다.
 * @summary 조직 목록 조회
 */
export const coreControllerGetOrganizationsV1 = (
    params?: CoreControllerGetOrganizationsV1Params,
 signal?: AbortSignal
) => {


      return coreControllerGetOrganizationsV1Mutator<CoreControllerGetOrganizationsV1200>(
      {url: `/api/v1/organizations`, method: 'GET',
        params, signal
    },
      );
    }




export const getCoreControllerGetOrganizationsV1QueryKey = (params?: CoreControllerGetOrganizationsV1Params,) => {
    return [
    `/api/v1/organizations`, ...(params ? [params] : [])
    ] as const;
    }


export const getCoreControllerGetOrganizationsV1QueryOptions = <TData = Awaited<ReturnType<typeof coreControllerGetOrganizationsV1>>, TError = CoreControllerGetOrganizationsV1ErrorType<unknown>>(params?: CoreControllerGetOrganizationsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetOrganizationsV1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCoreControllerGetOrganizationsV1QueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof coreControllerGetOrganizationsV1>>> = ({ signal }) => coreControllerGetOrganizationsV1(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetOrganizationsV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CoreControllerGetOrganizationsV1QueryResult = NonNullable<Awaited<ReturnType<typeof coreControllerGetOrganizationsV1>>>
export type CoreControllerGetOrganizationsV1QueryError = CoreControllerGetOrganizationsV1ErrorType<unknown>


export function useCoreControllerGetOrganizationsV1<TData = Awaited<ReturnType<typeof coreControllerGetOrganizationsV1>>, TError = CoreControllerGetOrganizationsV1ErrorType<unknown>>(
 params: undefined |  CoreControllerGetOrganizationsV1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetOrganizationsV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof coreControllerGetOrganizationsV1>>,
          TError,
          Awaited<ReturnType<typeof coreControllerGetOrganizationsV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCoreControllerGetOrganizationsV1<TData = Awaited<ReturnType<typeof coreControllerGetOrganizationsV1>>, TError = CoreControllerGetOrganizationsV1ErrorType<unknown>>(
 params?: CoreControllerGetOrganizationsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetOrganizationsV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof coreControllerGetOrganizationsV1>>,
          TError,
          Awaited<ReturnType<typeof coreControllerGetOrganizationsV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCoreControllerGetOrganizationsV1<TData = Awaited<ReturnType<typeof coreControllerGetOrganizationsV1>>, TError = CoreControllerGetOrganizationsV1ErrorType<unknown>>(
 params?: CoreControllerGetOrganizationsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetOrganizationsV1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 조직 목록 조회
 */

export function useCoreControllerGetOrganizationsV1<TData = Awaited<ReturnType<typeof coreControllerGetOrganizationsV1>>, TError = CoreControllerGetOrganizationsV1ErrorType<unknown>>(
 params?: CoreControllerGetOrganizationsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetOrganizationsV1>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCoreControllerGetOrganizationsV1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * 가입 대기 중인 조직을 승인합니다.
 * @summary 조직 승인
 */
export const coreControllerApproveOrganizationV1 = (
    id: string,
 signal?: AbortSignal
) => {


      return coreControllerApproveOrganizationV1Mutator<ApiResponse>(
      {url: `/api/v1/organizations/${id}/approve`, method: 'PATCH', signal
    },
      );
    }



export const getCoreControllerApproveOrganizationV1MutationOptions = <TError = CoreControllerApproveOrganizationV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof coreControllerApproveOrganizationV1>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof coreControllerApproveOrganizationV1>>, TError,{id: string}, TContext> => {

const mutationKey = ['coreControllerApproveOrganizationV1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof coreControllerApproveOrganizationV1>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  coreControllerApproveOrganizationV1(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CoreControllerApproveOrganizationV1MutationResult = NonNullable<Awaited<ReturnType<typeof coreControllerApproveOrganizationV1>>>

    export type CoreControllerApproveOrganizationV1MutationError = CoreControllerApproveOrganizationV1ErrorType<unknown>

    /**
 * @summary 조직 승인
 */
export const useCoreControllerApproveOrganizationV1 = <TError = CoreControllerApproveOrganizationV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof coreControllerApproveOrganizationV1>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof coreControllerApproveOrganizationV1>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getCoreControllerApproveOrganizationV1MutationOptions(options), queryClient);
    }

/**
 * 가입 대기 중인 조직을 거절합니다.
 * @summary 조직 거절
 */
export const coreControllerRejectOrganizationV1 = (
    id: string,
 signal?: AbortSignal
) => {


      return coreControllerRejectOrganizationV1Mutator<ApiResponse>(
      {url: `/api/v1/organizations/${id}/reject`, method: 'PATCH', signal
    },
      );
    }



export const getCoreControllerRejectOrganizationV1MutationOptions = <TError = CoreControllerRejectOrganizationV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof coreControllerRejectOrganizationV1>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof coreControllerRejectOrganizationV1>>, TError,{id: string}, TContext> => {

const mutationKey = ['coreControllerRejectOrganizationV1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof coreControllerRejectOrganizationV1>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  coreControllerRejectOrganizationV1(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CoreControllerRejectOrganizationV1MutationResult = NonNullable<Awaited<ReturnType<typeof coreControllerRejectOrganizationV1>>>

    export type CoreControllerRejectOrganizationV1MutationError = CoreControllerRejectOrganizationV1ErrorType<unknown>

    /**
 * @summary 조직 거절
 */
export const useCoreControllerRejectOrganizationV1 = <TError = CoreControllerRejectOrganizationV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof coreControllerRejectOrganizationV1>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof coreControllerRejectOrganizationV1>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getCoreControllerRejectOrganizationV1MutationOptions(options), queryClient);
    }

/**
 * 플랫폼 공지사항 목록을 조회합니다.
 * @summary 공지사항 조회
 */
export const coreControllerGetAnnouncementsV1 = (
    params?: CoreControllerGetAnnouncementsV1Params,
 signal?: AbortSignal
) => {


      return coreControllerGetAnnouncementsV1Mutator<CoreControllerGetAnnouncementsV1200>(
      {url: `/api/v1/announcements`, method: 'GET',
        params, signal
    },
      );
    }




export const getCoreControllerGetAnnouncementsV1QueryKey = (params?: CoreControllerGetAnnouncementsV1Params,) => {
    return [
    `/api/v1/announcements`, ...(params ? [params] : [])
    ] as const;
    }


export const getCoreControllerGetAnnouncementsV1QueryOptions = <TData = Awaited<ReturnType<typeof coreControllerGetAnnouncementsV1>>, TError = CoreControllerGetAnnouncementsV1ErrorType<unknown>>(params?: CoreControllerGetAnnouncementsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetAnnouncementsV1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCoreControllerGetAnnouncementsV1QueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof coreControllerGetAnnouncementsV1>>> = ({ signal }) => coreControllerGetAnnouncementsV1(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetAnnouncementsV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CoreControllerGetAnnouncementsV1QueryResult = NonNullable<Awaited<ReturnType<typeof coreControllerGetAnnouncementsV1>>>
export type CoreControllerGetAnnouncementsV1QueryError = CoreControllerGetAnnouncementsV1ErrorType<unknown>


export function useCoreControllerGetAnnouncementsV1<TData = Awaited<ReturnType<typeof coreControllerGetAnnouncementsV1>>, TError = CoreControllerGetAnnouncementsV1ErrorType<unknown>>(
 params: undefined |  CoreControllerGetAnnouncementsV1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetAnnouncementsV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof coreControllerGetAnnouncementsV1>>,
          TError,
          Awaited<ReturnType<typeof coreControllerGetAnnouncementsV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCoreControllerGetAnnouncementsV1<TData = Awaited<ReturnType<typeof coreControllerGetAnnouncementsV1>>, TError = CoreControllerGetAnnouncementsV1ErrorType<unknown>>(
 params?: CoreControllerGetAnnouncementsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetAnnouncementsV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof coreControllerGetAnnouncementsV1>>,
          TError,
          Awaited<ReturnType<typeof coreControllerGetAnnouncementsV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCoreControllerGetAnnouncementsV1<TData = Awaited<ReturnType<typeof coreControllerGetAnnouncementsV1>>, TError = CoreControllerGetAnnouncementsV1ErrorType<unknown>>(
 params?: CoreControllerGetAnnouncementsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetAnnouncementsV1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 공지사항 조회
 */

export function useCoreControllerGetAnnouncementsV1<TData = Awaited<ReturnType<typeof coreControllerGetAnnouncementsV1>>, TError = CoreControllerGetAnnouncementsV1ErrorType<unknown>>(
 params?: CoreControllerGetAnnouncementsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetAnnouncementsV1>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCoreControllerGetAnnouncementsV1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * 새로운 공지사항을 작성합니다.
 * @summary 공지사항 작성
 */
export const coreControllerCreateAnnouncementV1 = (
    createAnnouncementDto: CreateAnnouncementDto,
 signal?: AbortSignal
) => {


      return coreControllerCreateAnnouncementV1Mutator<CoreControllerCreateAnnouncementV1200>(
      {url: `/api/v1/announcements`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAnnouncementDto, signal
    },
      );
    }



export const getCoreControllerCreateAnnouncementV1MutationOptions = <TError = CoreControllerCreateAnnouncementV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof coreControllerCreateAnnouncementV1>>, TError,{data: CreateAnnouncementDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof coreControllerCreateAnnouncementV1>>, TError,{data: CreateAnnouncementDto}, TContext> => {

const mutationKey = ['coreControllerCreateAnnouncementV1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof coreControllerCreateAnnouncementV1>>, {data: CreateAnnouncementDto}> = (props) => {
          const {data} = props ?? {};

          return  coreControllerCreateAnnouncementV1(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CoreControllerCreateAnnouncementV1MutationResult = NonNullable<Awaited<ReturnType<typeof coreControllerCreateAnnouncementV1>>>
    export type CoreControllerCreateAnnouncementV1MutationBody = CreateAnnouncementDto
    export type CoreControllerCreateAnnouncementV1MutationError = CoreControllerCreateAnnouncementV1ErrorType<unknown>

    /**
 * @summary 공지사항 작성
 */
export const useCoreControllerCreateAnnouncementV1 = <TError = CoreControllerCreateAnnouncementV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof coreControllerCreateAnnouncementV1>>, TError,{data: CreateAnnouncementDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof coreControllerCreateAnnouncementV1>>,
        TError,
        {data: CreateAnnouncementDto},
        TContext
      > => {
      return useMutation(getCoreControllerCreateAnnouncementV1MutationOptions(options), queryClient);
    }

/**
 * 플랫폼 고객지원 티켓 목록을 조회합니다.
 * @summary 고객지원 티켓 조회
 */
export const coreControllerGetTicketsV1 = (
    params?: CoreControllerGetTicketsV1Params,
 signal?: AbortSignal
) => {


      return coreControllerGetTicketsV1Mutator<CoreControllerGetTicketsV1200>(
      {url: `/api/v1/support/tickets`, method: 'GET',
        params, signal
    },
      );
    }




export const getCoreControllerGetTicketsV1QueryKey = (params?: CoreControllerGetTicketsV1Params,) => {
    return [
    `/api/v1/support/tickets`, ...(params ? [params] : [])
    ] as const;
    }


export const getCoreControllerGetTicketsV1QueryOptions = <TData = Awaited<ReturnType<typeof coreControllerGetTicketsV1>>, TError = CoreControllerGetTicketsV1ErrorType<unknown>>(params?: CoreControllerGetTicketsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetTicketsV1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCoreControllerGetTicketsV1QueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof coreControllerGetTicketsV1>>> = ({ signal }) => coreControllerGetTicketsV1(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetTicketsV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CoreControllerGetTicketsV1QueryResult = NonNullable<Awaited<ReturnType<typeof coreControllerGetTicketsV1>>>
export type CoreControllerGetTicketsV1QueryError = CoreControllerGetTicketsV1ErrorType<unknown>


export function useCoreControllerGetTicketsV1<TData = Awaited<ReturnType<typeof coreControllerGetTicketsV1>>, TError = CoreControllerGetTicketsV1ErrorType<unknown>>(
 params: undefined |  CoreControllerGetTicketsV1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetTicketsV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof coreControllerGetTicketsV1>>,
          TError,
          Awaited<ReturnType<typeof coreControllerGetTicketsV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCoreControllerGetTicketsV1<TData = Awaited<ReturnType<typeof coreControllerGetTicketsV1>>, TError = CoreControllerGetTicketsV1ErrorType<unknown>>(
 params?: CoreControllerGetTicketsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetTicketsV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof coreControllerGetTicketsV1>>,
          TError,
          Awaited<ReturnType<typeof coreControllerGetTicketsV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCoreControllerGetTicketsV1<TData = Awaited<ReturnType<typeof coreControllerGetTicketsV1>>, TError = CoreControllerGetTicketsV1ErrorType<unknown>>(
 params?: CoreControllerGetTicketsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetTicketsV1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 고객지원 티켓 조회
 */

export function useCoreControllerGetTicketsV1<TData = Awaited<ReturnType<typeof coreControllerGetTicketsV1>>, TError = CoreControllerGetTicketsV1ErrorType<unknown>>(
 params?: CoreControllerGetTicketsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetTicketsV1>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCoreControllerGetTicketsV1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * 플랫폼/조직 범위의 현재 활성 약관 목록을 조회합니다.
 * @summary 약관 목록 조회
 */
export const coreControllerGetActiveTermsV1 = (
    params?: CoreControllerGetActiveTermsV1Params,
 signal?: AbortSignal
) => {


      return coreControllerGetActiveTermsV1Mutator<CoreControllerGetActiveTermsV1200>(
      {url: `/api/v1/terms`, method: 'GET',
        params, signal
    },
      );
    }




export const getCoreControllerGetActiveTermsV1QueryKey = (params?: CoreControllerGetActiveTermsV1Params,) => {
    return [
    `/api/v1/terms`, ...(params ? [params] : [])
    ] as const;
    }


export const getCoreControllerGetActiveTermsV1QueryOptions = <TData = Awaited<ReturnType<typeof coreControllerGetActiveTermsV1>>, TError = CoreControllerGetActiveTermsV1ErrorType<unknown>>(params?: CoreControllerGetActiveTermsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetActiveTermsV1>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCoreControllerGetActiveTermsV1QueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof coreControllerGetActiveTermsV1>>> = ({ signal }) => coreControllerGetActiveTermsV1(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetActiveTermsV1>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CoreControllerGetActiveTermsV1QueryResult = NonNullable<Awaited<ReturnType<typeof coreControllerGetActiveTermsV1>>>
export type CoreControllerGetActiveTermsV1QueryError = CoreControllerGetActiveTermsV1ErrorType<unknown>


export function useCoreControllerGetActiveTermsV1<TData = Awaited<ReturnType<typeof coreControllerGetActiveTermsV1>>, TError = CoreControllerGetActiveTermsV1ErrorType<unknown>>(
 params: undefined |  CoreControllerGetActiveTermsV1Params, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetActiveTermsV1>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof coreControllerGetActiveTermsV1>>,
          TError,
          Awaited<ReturnType<typeof coreControllerGetActiveTermsV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCoreControllerGetActiveTermsV1<TData = Awaited<ReturnType<typeof coreControllerGetActiveTermsV1>>, TError = CoreControllerGetActiveTermsV1ErrorType<unknown>>(
 params?: CoreControllerGetActiveTermsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetActiveTermsV1>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof coreControllerGetActiveTermsV1>>,
          TError,
          Awaited<ReturnType<typeof coreControllerGetActiveTermsV1>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCoreControllerGetActiveTermsV1<TData = Awaited<ReturnType<typeof coreControllerGetActiveTermsV1>>, TError = CoreControllerGetActiveTermsV1ErrorType<unknown>>(
 params?: CoreControllerGetActiveTermsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetActiveTermsV1>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 약관 목록 조회
 */

export function useCoreControllerGetActiveTermsV1<TData = Awaited<ReturnType<typeof coreControllerGetActiveTermsV1>>, TError = CoreControllerGetActiveTermsV1ErrorType<unknown>>(
 params?: CoreControllerGetActiveTermsV1Params, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof coreControllerGetActiveTermsV1>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCoreControllerGetActiveTermsV1QueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * PLATFORM 또는 ORGANIZATION 그룹 약관 문서를 생성합니다.
 * @summary 약관 문서 생성
 */
export const coreControllerCreateTermsDocumentV1 = (
    createTermsDocumentDto: CreateTermsDocumentDto,
 signal?: AbortSignal
) => {


      return coreControllerCreateTermsDocumentV1Mutator<CoreControllerCreateTermsDocumentV1200>(
      {url: `/api/v1/terms/documents`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTermsDocumentDto, signal
    },
      );
    }



export const getCoreControllerCreateTermsDocumentV1MutationOptions = <TError = CoreControllerCreateTermsDocumentV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof coreControllerCreateTermsDocumentV1>>, TError,{data: CreateTermsDocumentDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof coreControllerCreateTermsDocumentV1>>, TError,{data: CreateTermsDocumentDto}, TContext> => {

const mutationKey = ['coreControllerCreateTermsDocumentV1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof coreControllerCreateTermsDocumentV1>>, {data: CreateTermsDocumentDto}> = (props) => {
          const {data} = props ?? {};

          return  coreControllerCreateTermsDocumentV1(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CoreControllerCreateTermsDocumentV1MutationResult = NonNullable<Awaited<ReturnType<typeof coreControllerCreateTermsDocumentV1>>>
    export type CoreControllerCreateTermsDocumentV1MutationBody = CreateTermsDocumentDto
    export type CoreControllerCreateTermsDocumentV1MutationError = CoreControllerCreateTermsDocumentV1ErrorType<unknown>

    /**
 * @summary 약관 문서 생성
 */
export const useCoreControllerCreateTermsDocumentV1 = <TError = CoreControllerCreateTermsDocumentV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof coreControllerCreateTermsDocumentV1>>, TError,{data: CreateTermsDocumentDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof coreControllerCreateTermsDocumentV1>>,
        TError,
        {data: CreateTermsDocumentDto},
        TContext
      > => {
      return useMutation(getCoreControllerCreateTermsDocumentV1MutationOptions(options), queryClient);
    }

/**
 * 약관 버전을 생성하고 선택적으로 즉시 게시합니다.
 * @summary 약관 버전 생성
 */
export const coreControllerCreateTermsVersionV1 = (
    createTermsVersionDto: CreateTermsVersionDto,
 signal?: AbortSignal
) => {


      return coreControllerCreateTermsVersionV1Mutator<CoreControllerCreateTermsVersionV1200>(
      {url: `/api/v1/terms/versions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTermsVersionDto, signal
    },
      );
    }



export const getCoreControllerCreateTermsVersionV1MutationOptions = <TError = CoreControllerCreateTermsVersionV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof coreControllerCreateTermsVersionV1>>, TError,{data: CreateTermsVersionDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof coreControllerCreateTermsVersionV1>>, TError,{data: CreateTermsVersionDto}, TContext> => {

const mutationKey = ['coreControllerCreateTermsVersionV1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof coreControllerCreateTermsVersionV1>>, {data: CreateTermsVersionDto}> = (props) => {
          const {data} = props ?? {};

          return  coreControllerCreateTermsVersionV1(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CoreControllerCreateTermsVersionV1MutationResult = NonNullable<Awaited<ReturnType<typeof coreControllerCreateTermsVersionV1>>>
    export type CoreControllerCreateTermsVersionV1MutationBody = CreateTermsVersionDto
    export type CoreControllerCreateTermsVersionV1MutationError = CoreControllerCreateTermsVersionV1ErrorType<unknown>

    /**
 * @summary 약관 버전 생성
 */
export const useCoreControllerCreateTermsVersionV1 = <TError = CoreControllerCreateTermsVersionV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof coreControllerCreateTermsVersionV1>>, TError,{data: CreateTermsVersionDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof coreControllerCreateTermsVersionV1>>,
        TError,
        {data: CreateTermsVersionDto},
        TContext
      > => {
      return useMutation(getCoreControllerCreateTermsVersionV1MutationOptions(options), queryClient);
    }

/**
 * 매니저의 특정 약관 버전 동의 이력을 저장합니다.
 * @summary 약관 동의 저장
 */
export const coreControllerAgreeTermsV1 = (
    agreeTermsDto: AgreeTermsDto,
 signal?: AbortSignal
) => {


      return coreControllerAgreeTermsV1Mutator<CoreControllerAgreeTermsV1200>(
      {url: `/api/v1/terms/agreements`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: agreeTermsDto, signal
    },
      );
    }



export const getCoreControllerAgreeTermsV1MutationOptions = <TError = CoreControllerAgreeTermsV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof coreControllerAgreeTermsV1>>, TError,{data: AgreeTermsDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof coreControllerAgreeTermsV1>>, TError,{data: AgreeTermsDto}, TContext> => {

const mutationKey = ['coreControllerAgreeTermsV1'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof coreControllerAgreeTermsV1>>, {data: AgreeTermsDto}> = (props) => {
          const {data} = props ?? {};

          return  coreControllerAgreeTermsV1(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CoreControllerAgreeTermsV1MutationResult = NonNullable<Awaited<ReturnType<typeof coreControllerAgreeTermsV1>>>
    export type CoreControllerAgreeTermsV1MutationBody = AgreeTermsDto
    export type CoreControllerAgreeTermsV1MutationError = CoreControllerAgreeTermsV1ErrorType<unknown>

    /**
 * @summary 약관 동의 저장
 */
export const useCoreControllerAgreeTermsV1 = <TError = CoreControllerAgreeTermsV1ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof coreControllerAgreeTermsV1>>, TError,{data: AgreeTermsDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof coreControllerAgreeTermsV1>>,
        TError,
        {data: AgreeTermsDto},
        TContext
      > => {
      return useMutation(getCoreControllerAgreeTermsV1MutationOptions(options), queryClient);
    }

export const healthControllerLive = (

 signal?: AbortSignal
) => {


      return healthControllerLiveMutator<HealthControllerLive200>(
      {url: `/health/live`, method: 'GET', signal
    },
      );
    }




export const getHealthControllerLiveQueryKey = () => {
    return [
    `/health/live`
    ] as const;
    }


export const getHealthControllerLiveQueryOptions = <TData = Awaited<ReturnType<typeof healthControllerLive>>, TError = HealthControllerLiveErrorType<HealthControllerLive503>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerLive>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthControllerLiveQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthControllerLive>>> = ({ signal }) => healthControllerLive(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthControllerLive>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthControllerLiveQueryResult = NonNullable<Awaited<ReturnType<typeof healthControllerLive>>>
export type HealthControllerLiveQueryError = HealthControllerLiveErrorType<HealthControllerLive503>


export function useHealthControllerLive<TData = Awaited<ReturnType<typeof healthControllerLive>>, TError = HealthControllerLiveErrorType<HealthControllerLive503>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerLive>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerLive>>,
          TError,
          Awaited<ReturnType<typeof healthControllerLive>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthControllerLive<TData = Awaited<ReturnType<typeof healthControllerLive>>, TError = HealthControllerLiveErrorType<HealthControllerLive503>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerLive>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerLive>>,
          TError,
          Awaited<ReturnType<typeof healthControllerLive>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthControllerLive<TData = Awaited<ReturnType<typeof healthControllerLive>>, TError = HealthControllerLiveErrorType<HealthControllerLive503>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerLive>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useHealthControllerLive<TData = Awaited<ReturnType<typeof healthControllerLive>>, TError = HealthControllerLiveErrorType<HealthControllerLive503>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerLive>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthControllerLiveQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const healthControllerReady = (

 signal?: AbortSignal
) => {


      return healthControllerReadyMutator<HealthControllerReady200>(
      {url: `/health/ready`, method: 'GET', signal
    },
      );
    }




export const getHealthControllerReadyQueryKey = () => {
    return [
    `/health/ready`
    ] as const;
    }


export const getHealthControllerReadyQueryOptions = <TData = Awaited<ReturnType<typeof healthControllerReady>>, TError = HealthControllerReadyErrorType<HealthControllerReady503>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerReady>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthControllerReadyQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthControllerReady>>> = ({ signal }) => healthControllerReady(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthControllerReady>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthControllerReadyQueryResult = NonNullable<Awaited<ReturnType<typeof healthControllerReady>>>
export type HealthControllerReadyQueryError = HealthControllerReadyErrorType<HealthControllerReady503>


export function useHealthControllerReady<TData = Awaited<ReturnType<typeof healthControllerReady>>, TError = HealthControllerReadyErrorType<HealthControllerReady503>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerReady>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerReady>>,
          TError,
          Awaited<ReturnType<typeof healthControllerReady>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthControllerReady<TData = Awaited<ReturnType<typeof healthControllerReady>>, TError = HealthControllerReadyErrorType<HealthControllerReady503>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerReady>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerReady>>,
          TError,
          Awaited<ReturnType<typeof healthControllerReady>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthControllerReady<TData = Awaited<ReturnType<typeof healthControllerReady>>, TError = HealthControllerReadyErrorType<HealthControllerReady503>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerReady>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useHealthControllerReady<TData = Awaited<ReturnType<typeof healthControllerReady>>, TError = HealthControllerReadyErrorType<HealthControllerReady503>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthControllerReady>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthControllerReadyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







