/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';

export const announcementControllerGetAnnouncementPageV1QueryFilterIsPublishedDefault = false;
export const announcementControllerGetAnnouncementPageV1QueryPageDefault = 1;
export const announcementControllerGetAnnouncementPageV1QueryLimitDefault = 20;

export const AnnouncementControllerGetAnnouncementPageV1QueryParams = zod.object({
  "filter": zod.object({
  "isPublished": zod.boolean().default(announcementControllerGetAnnouncementPageV1QueryFilterIsPublishedDefault).describe('게시된 공지만 조회할지 여부'),
  "status": zod.enum(['DRAFT', 'SCHEDULED', 'ACTIVE', 'EXPIRED']).optional().describe('게시 상태')
}).describe('필터 조건'),
  "sort": zod.array(zod.string()).optional().describe('정렬 필드'),
  "direction": zod.array(zod.enum(['asc', 'desc'])).default([`desc`]).describe('정렬 방향'),
  "page": zod.unknown().default(announcementControllerGetAnnouncementPageV1QueryPageDefault).describe('페이지 번호'),
  "limit": zod.unknown().default(announcementControllerGetAnnouncementPageV1QueryLimitDefault).describe('페이지 크기')
})

export const AnnouncementControllerGetAnnouncementPageV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('공지사항 식별자'),
  "title": zod.string().describe('공지사항 제목'),
  "content": zod.string().describe('공지사항 본문 내용'),
  "createdAt": zod.iso.datetime({"offset":true}).describe('생성 일시'),
  "updatedAt": zod.iso.datetime({"offset":true}).describe('수정 일시'),
  "category": zod.enum(['NOTICE', 'MAINTENANCE', 'SECURITY', 'EVENT']).describe('공지 분류'),
  "audience": zod.enum(['ALL', 'PLATFORM', 'ORGANIZATION']).describe('공지 대상'),
  "channel": zod.enum(['IN_APP', 'EMAIL', 'PUSH']).describe('공지 채널'),
  "priority": zod.enum(['LOW', 'NORMAL', 'HIGH']).describe('공지 우선순위'),
  "pinned": zod.boolean().describe('상단 고정 여부'),
  "publishedAt": zod.iso.datetime({"offset":true}).optional().describe('게시 확정 일시'),
  "startAt": zod.iso.datetime({"offset":true}).optional().describe('게시 시작일'),
  "endAt": zod.iso.datetime({"offset":true}).optional().describe('게시 종료일'),
  "status": zod.enum(['DRAFT', 'SCHEDULED', 'ACTIVE', 'EXPIRED']).describe('게시 상태'),
  "isPublished": zod.boolean().describe('게시 확정 여부'),
  "author": zod.string().describe('작성자')
})).describe('공지사항 목록'),
  "totalCount": zod.number().describe('전체 개수'),
  "page": zod.number().describe('페이지 번호'),
  "limit": zod.number().describe('페이지 크기'),
  "totalPages": zod.number().describe('전체 페이지 수'),
  "hasNextPage": zod.boolean().describe('다음 페이지 존재 여부'),
  "hasPrevPage": zod.boolean().describe('이전 페이지 존재 여부')
}).optional()
}))


export const AnnouncementControllerCreateAnnouncementV1Body = zod.object({
  "title": zod.string().describe('공지사항 제목'),
  "content": zod.string().describe('공지사항 본문'),
  "category": zod.enum(['NOTICE', 'MAINTENANCE', 'SECURITY', 'EVENT']).optional().describe('공지 분류'),
  "audience": zod.enum(['ALL', 'PLATFORM', 'ORGANIZATION']).optional().describe('공지 대상'),
  "channel": zod.enum(['IN_APP', 'EMAIL', 'PUSH']).optional().describe('공지 채널'),
  "priority": zod.enum(['LOW', 'NORMAL', 'HIGH']).optional().describe('공지 우선순위'),
  "pinned": zod.boolean().optional().describe('공지 목록에서 우선 노출할지 여부'),
  "publishedAt": zod.iso.datetime({"offset":true}).optional().describe('게시 확정 일시'),
  "startAt": zod.iso.datetime({"offset":true}).optional().describe('게시 시작일'),
  "endAt": zod.iso.datetime({"offset":true}).optional().describe('게시 종료일')
})


export const AnnouncementControllerGetAnnouncementV1Params = zod.object({
  "id": zod.string()
})

export const AnnouncementControllerGetAnnouncementV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('공지사항 식별자'),
  "title": zod.string().describe('공지사항 제목'),
  "content": zod.string().describe('공지사항 본문 내용'),
  "createdAt": zod.iso.datetime({"offset":true}).describe('생성 일시'),
  "updatedAt": zod.iso.datetime({"offset":true}).describe('수정 일시'),
  "category": zod.enum(['NOTICE', 'MAINTENANCE', 'SECURITY', 'EVENT']).describe('공지 분류'),
  "audience": zod.enum(['ALL', 'PLATFORM', 'ORGANIZATION']).describe('공지 대상'),
  "channel": zod.enum(['IN_APP', 'EMAIL', 'PUSH']).describe('공지 채널'),
  "priority": zod.enum(['LOW', 'NORMAL', 'HIGH']).describe('공지 우선순위'),
  "pinned": zod.boolean().describe('상단 고정 여부'),
  "publishedAt": zod.iso.datetime({"offset":true}).optional().describe('게시 확정 일시'),
  "startAt": zod.iso.datetime({"offset":true}).optional().describe('게시 시작일'),
  "endAt": zod.iso.datetime({"offset":true}).optional().describe('게시 종료일'),
  "status": zod.enum(['DRAFT', 'SCHEDULED', 'ACTIVE', 'EXPIRED']).describe('게시 상태'),
  "isPublished": zod.boolean().describe('게시 확정 여부'),
  "author": zod.string().describe('작성자')
}).optional()
}))


export const AnnouncementControllerUpdateAnnouncementV1Params = zod.object({
  "id": zod.string()
})

export const AnnouncementControllerUpdateAnnouncementV1Body = zod.object({
  "id": zod.string().describe('공지사항 식별자'),
  "title": zod.string().describe('공지사항 제목'),
  "content": zod.string().describe('공지사항 본문'),
  "category": zod.enum(['NOTICE', 'MAINTENANCE', 'SECURITY', 'EVENT']).optional().describe('공지 분류'),
  "audience": zod.enum(['ALL', 'PLATFORM', 'ORGANIZATION']).optional().describe('공지 대상'),
  "channel": zod.enum(['IN_APP', 'EMAIL', 'PUSH']).optional().describe('공지 채널'),
  "priority": zod.enum(['LOW', 'NORMAL', 'HIGH']).optional().describe('공지 우선순위'),
  "isPublished": zod.boolean().optional().describe('게시 유무'),
  "pinned": zod.boolean().optional().describe('공지 목록에서 우선 노출할지 여부'),
  "publishedAt": zod.iso.datetime({"offset":true}).optional().describe('게시 확정 일시'),
  "startAt": zod.iso.datetime({"offset":true}).optional().describe('게시 시작일'),
  "endAt": zod.iso.datetime({"offset":true}).optional().describe('게시 종료일')
})

export const AnnouncementControllerUpdateAnnouncementV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('공지사항 식별자')
}).optional()
}))


export const AnnouncementControllerDeleteAnnouncementV1Params = zod.object({
  "id": zod.string()
})

export const AnnouncementControllerDeleteAnnouncementV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('공지사항 식별자')
}).optional()
}))


export const AuthControllerLoginV1Body = zod.object({
  "email": zod.string().describe('이메일 주소'),
  "password": zod.string().describe('비밀번호')
})


export const AuthControllerMeV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "account": zod.object({
  "id": zod.string().describe('계정 식별자'),
  "email": zod.string().describe('이메일 주소'),
  "status": zod.enum(['ACTIVE', 'INACTIVE']).describe('계정 상태'),
  "lastLoginAt": zod.looseObject({

}).optional().describe('마지막 로그인 일시'),
  "passwordExpiresAt": zod.iso.datetime({"offset":true}).describe('비밀번호 만료 일시'),
  "lockUntil": zod.looseObject({

}).optional().describe('잠금 해제 일시'),
  "isDormant": zod.boolean().describe('휴면 여부'),
  "isPasswordExpired": zod.boolean().describe('비밀번호 만료 여부')
}).describe('계정 정보'),
  "member": zod.object({
  "id": zod.string().describe('멤버 식별자'),
  "name": zod.string().describe('멤버 이름'),
  "status": zod.enum(['ACTIVE', 'INACTIVE']).describe('멤버 상태')
}).describe('멤버 정보'),
  "organization": zod.object({
  "id": zod.string().describe('조직 식별자'),
  "code": zod.string().describe('조직 코드'),
  "name": zod.string().describe('조직 이름'),
  "email": zod.string().describe('조직 이메일'),
  "status": zod.enum(['PENDING', 'ACTIVE', 'INACTIVE', 'REJECTED']).describe('조직 상태')
}).nullable().describe('조직 정보'),
  "permissions": zod.array(zod.string()).describe('권한 목록'),
  "agreedTermsVersionIds": zod.array(zod.string()).describe('현재 동의한 약관 버전 식별자 목록'),
  "mustAcceptTerms": zod.boolean().describe('약관 재동의 필요 여부')
}).optional()
}))


export const AuthControllerGetTermsV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().describe('약관 문서 식별자'),
  "code": zod.string().describe('약관 코드'),
  "title": zod.string().describe('약관 제목'),
  "required": zod.boolean().describe('필수 동의 여부'),
  "terminatedAt": zod.iso.datetime({"offset":true}).optional().describe('종료 일시'),
  "status": zod.enum(['DRAFT', 'PUBLISHED', 'TERMINATED']).describe('약관 상태'),
  "organization": zod.string().optional().describe('조직 식별자')
})).optional()
}))


export const AuthControllerAgreeTermsV1Body = zod.object({
  "member": zod.looseObject({

}).describe('멤버'),
  "termsVersion": zod.looseObject({

}).describe('동의할 약관 버전')
})


export const AuthControllerChangePasswordV1Body = zod.object({
  "currentPassword": zod.string().describe('현재 비밀번호'),
  "newPassword": zod.string().describe('새 비밀번호'),
  "confirmPassword": zod.string().describe('새 비밀번호 확인')
})


export const HealthControllerLiveResponse = zod.object({
  "status": zod.string().optional(),
  "info": zod.record(zod.string(), zod.object({
  "status": zod.string()
})).nullish(),
  "error": zod.record(zod.string(), zod.object({
  "status": zod.string()
})).nullish(),
  "details": zod.record(zod.string(), zod.object({
  "status": zod.string()
})).optional()
})


export const HealthControllerReadyResponse = zod.object({
  "status": zod.string().optional(),
  "info": zod.record(zod.string(), zod.object({
  "status": zod.string()
})).nullish(),
  "error": zod.record(zod.string(), zod.object({
  "status": zod.string()
})).nullish(),
  "details": zod.record(zod.string(), zod.object({
  "status": zod.string()
})).optional()
})


export const I18nControllerGetLocalesV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "code": zod.string().describe('로케일 코드'),
  "name": zod.string().describe('로케일 이름'),
  "regionCode": zod.string().nullish().describe('지역 코드'),
  "direction": zod.enum(['ltr', 'rtl']).describe('문자 방향'),
  "isActive": zod.boolean().describe('활성화 여부'),
  "sortOrder": zod.number().nullish().describe('정렬 순서')
})).describe('활성 로케일 목록')
}).optional()
}))


export const MembersControllerCreateInviteV1Body = zod.object({
  "name": zod.string().describe('초대할 사람 이름'),
  "email": zod.string().describe('초대할 사람 이메일'),
  "role": zod.string().describe('부여할 역할'),
  "note": zod.string().optional().describe('메모\/메모사항')
})


export const MembersControllerToggleMemberStatusV1Body = zod.object({
  "id": zod.string().describe('멤버 식별자'),
  "status": zod.enum(['ACTIVE', 'INACTIVE']).describe('변경할 상태')
})


export const MembersControllerUpdateMemberRoleV1Body = zod.object({
  "id": zod.string().describe('멤버 식별자'),
  "role": zod.looseObject({

}).describe('변경할 역할')
})


export const membersControllerGetMemberPageV1QueryPageDefault = 1;
export const membersControllerGetMemberPageV1QueryLimitDefault = 20;

export const MembersControllerGetMemberPageV1QueryParams = zod.object({
  "sort": zod.array(zod.string()).optional().describe('정렬 필드'),
  "direction": zod.array(zod.enum(['asc', 'desc'])).default([`desc`]).describe('정렬 방향'),
  "page": zod.number().default(membersControllerGetMemberPageV1QueryPageDefault).describe('페이지 번호'),
  "limit": zod.number().default(membersControllerGetMemberPageV1QueryLimitDefault).describe('페이지 크기'),
  "filters": zod.looseObject({

}).optional().describe('필터 조건')
})

export const MembersControllerGetMemberPageV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('멤버 식별자'),
  "name": zod.string().describe('멤버 이름'),
  "email": zod.string().describe('이메일'),
  "status": zod.enum(['ACTIVE', 'INACTIVE']).describe('멤버 상태'),
  "roles": zod.array(zod.string()).optional().describe('권한 목록'),
  "lastLoginAt": zod.iso.datetime({"offset":true}).optional().describe('최근 로그인'),
  "createdAt": zod.iso.datetime({"offset":true}).describe('생성 일시')
})).describe('멤버 목록'),
  "totalCount": zod.number().describe('전체 개수'),
  "page": zod.number().describe('페이지 번호'),
  "limit": zod.number().describe('페이지 크기'),
  "totalPages": zod.number().describe('전체 페이지 수'),
  "hasNextPage": zod.boolean().describe('다음 페이지 존재 여부'),
  "hasPrevPage": zod.boolean().describe('이전 페이지 존재 여부')
}).optional()
}))


export const MembersControllerGetMemberV1Params = zod.object({
  "id": zod.string()
})

export const MembersControllerGetMemberV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('멤버 식별자'),
  "name": zod.string().describe('멤버 이름'),
  "email": zod.string().describe('이메일'),
  "status": zod.enum(['ACTIVE', 'INACTIVE']).describe('멤버 상태'),
  "roles": zod.array(zod.string()).describe('권한 목록'),
  "lastLoginAt": zod.iso.datetime({"offset":true}).nullable().describe('최근 로그인'),
  "createdAt": zod.iso.datetime({"offset":true}).describe('생성 일시')
}).optional()
}))


export const organizationControllerGetOrganizationPageV1QueryOffsetDefault = 0;
export const organizationControllerGetOrganizationPageV1QueryLimitDefault = 20;

export const OrganizationControllerGetOrganizationPageV1QueryParams = zod.object({
  "sort": zod.array(zod.string()).optional().describe('정렬 필드'),
  "direction": zod.array(zod.enum(['asc', 'desc'])).default([`desc`]).describe('정렬 방향'),
  "offset": zod.number().default(organizationControllerGetOrganizationPageV1QueryOffsetDefault).describe('오프셋'),
  "limit": zod.number().default(organizationControllerGetOrganizationPageV1QueryLimitDefault).describe('페이지 크기'),
  "filters": zod.object({
  "status": zod.enum(['PENDING', 'ACTIVE', 'INACTIVE', 'REJECTED']).optional().describe('메타데이터 날짜로 유추되는 조직 상태 필터')
}).optional().describe('필터 조건')
})

export const OrganizationControllerGetOrganizationPageV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('조직 식별자'),
  "name": zod.string().describe('조직 이름'),
  "createdAt": zod.iso.datetime({"offset":true}).describe('생성 일시'),
  "code": zod.string().describe('조직 코드'),
  "status": zod.enum(['PENDING', 'ACTIVE', 'INACTIVE', 'REJECTED']).describe('조직 상태')
})).describe('조직 목록')
}).optional()
}))


export const OrganizationControllerGetOrganizationRolesV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().describe('조직 역할 식별자'),
  "code": zod.string().describe('조직 역할 코드'),
  "name": zod.string().describe('조직 역할 이름'),
  "description": zod.string().optional().describe('조직 역할 설명')
})).optional()
}))


export const OrganizationControllerApproveOrganizationV1Params = zod.object({
  "id": zod.string()
})

export const OrganizationControllerApproveOrganizationV1Body = zod.object({
  "id": zod.string().optional().describe('조직 식별자'),
  "approve": zod.boolean().describe('승인 여부')
})

export const OrganizationControllerApproveOrganizationV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('조직 식별자')
}).optional()
}))


export const ResourceControllerGetPermissionSetsV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().describe('권한 세트 식별자'),
  "code": zod.string().describe('권한 세트 코드'),
  "name": zod.string().describe('권한 세트 이름'),
  "description": zod.string().optional().describe('권한 세트 설명'),
  "permissions": zod.array(zod.string()).describe('권한 코드 목록')
})).optional()
}))


export const ResourceControllerGetResourceV1Params = zod.object({
  "id": zod.string()
})

export const ResourceControllerGetResourceV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('리소스 식별자'),
  "code": zod.string().describe('리소스 코드'),
  "name": zod.string().describe('리소스 이름'),
  "type": zod.enum(['MENU', 'COMPONENT']).describe('리소스 유형'),
  "scope": zod.enum(['PLATFORM', 'ORGANIZATION']).describe('리소스 관리 범위'),
  "path": zod.string().optional().describe('리소스 경로'),
  "icon": zod.string().optional().describe('아이콘'),
  "sortOrder": zod.number().optional().describe('정렬 순서'),
  "actions": zod.array(zod.enum(['CREATE', 'READ', 'UPDATE', 'DELETE'])).describe('리소스 액션 목록'),
  "parent": zod.string().optional().describe('부모 리소스 식별자'),
  "children": zod.array(zod.unknown()).describe('하위 리소스 목록')
}).optional()
}))


export const resourceControllerGetResourcePageV1QuerySortDefault = [`sortOrder`, `code`];
export const resourceControllerGetResourcePageV1QueryOffsetDefault = 0;
export const resourceControllerGetResourcePageV1QueryLimitDefault = 20;

export const ResourceControllerGetResourcePageV1QueryParams = zod.object({
  "sort": zod.array(zod.string()).default(resourceControllerGetResourcePageV1QuerySortDefault).describe('정렬 필드'),
  "direction": zod.array(zod.enum(['asc', 'desc'])).default([`asc`, `asc`]).describe('정렬 방향'),
  "offset": zod.number().default(resourceControllerGetResourcePageV1QueryOffsetDefault).describe('오프셋'),
  "limit": zod.number().default(resourceControllerGetResourcePageV1QueryLimitDefault).describe('페이지 크기'),
  "filters": zod.object({
  "scope": zod.enum(['PLATFORM', 'ORGANIZATION']).describe('리소스 관리 범위')
}).describe('필터 조건')
})

export const ResourceControllerGetResourcePageV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().describe('리소스 식별자'),
  "code": zod.string().describe('리소스 코드'),
  "name": zod.string().describe('리소스 이름'),
  "type": zod.enum(['MENU', 'COMPONENT']).describe('리소스 유형'),
  "scope": zod.enum(['PLATFORM', 'ORGANIZATION']).describe('리소스 관리 범위'),
  "path": zod.string().optional().describe('리소스 경로'),
  "icon": zod.string().optional().describe('아이콘'),
  "sortOrder": zod.number().optional().describe('정렬 순서'),
  "actions": zod.array(zod.enum(['CREATE', 'READ', 'UPDATE', 'DELETE'])).describe('리소스 액션 목록'),
  "parent": zod.string().optional().describe('부모 리소스 식별자'),
  "children": zod.array(zod.unknown()).describe('하위 리소스 목록')
})).optional()
}))


export const supportControllerGetTicketPageV1QueryPageDefault = 1;
export const supportControllerGetTicketPageV1QueryLimitDefault = 20;

export const SupportControllerGetTicketPageV1QueryParams = zod.object({
  "sort": zod.array(zod.string()).optional().describe('정렬 필드'),
  "direction": zod.array(zod.enum(['asc', 'desc'])).default([`desc`]).describe('정렬 방향'),
  "page": zod.number().default(supportControllerGetTicketPageV1QueryPageDefault).describe('페이지 번호'),
  "limit": zod.number().default(supportControllerGetTicketPageV1QueryLimitDefault).describe('페이지 크기'),
  "filters": zod.object({
  "organization": zod.looseObject({

}).optional().describe('조직 필터'),
  "status": zod.enum(['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED']).optional().describe('티켓 상태 필터')
}).optional().describe('필터 조건')
})

export const SupportControllerGetTicketPageV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().describe('티켓 식별자'),
  "title": zod.string().describe('티켓 제목'),
  "content": zod.string().describe('티켓 내용'),
  "status": zod.enum(['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED']).describe('티켓 상태'),
  "priority": zod.enum(['LOW', 'MEDIUM', 'HIGH', 'URGENT']).describe('티켓 우선순위'),
  "createdAt": zod.iso.datetime({"offset":true}).describe('생성 일시'),
  "organization": zod.string().describe('조직 식별자')
})).optional()
}))


export const termsControllerGetTermsDocumentPageV1QueryOffsetDefault = 0;
export const termsControllerGetTermsDocumentPageV1QueryLimitDefault = 20;

export const TermsControllerGetTermsDocumentPageV1QueryParams = zod.object({
  "sort": zod.array(zod.string()).optional().describe('정렬 필드'),
  "direction": zod.array(zod.enum(['asc', 'desc'])).default([`desc`]).describe('정렬 방향'),
  "offset": zod.number().default(termsControllerGetTermsDocumentPageV1QueryOffsetDefault).describe('오프셋'),
  "limit": zod.number().default(termsControllerGetTermsDocumentPageV1QueryLimitDefault).describe('페이지 크기'),
  "filters": zod.object({
  "scope": zod.enum(['platform', 'organization']).optional().describe('조회 scope'),
  "status": zod.enum(['DRAFT', 'PUBLISHED', 'TERMINATED']).optional().describe('약관 상태 필터')
}).optional().describe('필터 조건')
})

export const TermsControllerGetTermsDocumentPageV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().describe('약관 문서 식별자'),
  "code": zod.string().describe('약관 코드'),
  "title": zod.string().describe('약관 제목'),
  "required": zod.boolean().describe('필수 동의 여부'),
  "terminatedAt": zod.iso.datetime({"offset":true}).optional().describe('종료 일시'),
  "status": zod.enum(['DRAFT', 'PUBLISHED', 'TERMINATED']).describe('약관 상태'),
  "organization": zod.string().optional().describe('조직 식별자')
})).optional()
}))


export const TermsControllerGetTermsDocumentV1Params = zod.object({
  "id": zod.string()
})

export const TermsControllerGetTermsDocumentV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "document": zod.object({
  "id": zod.string().describe('약관 문서 식별자'),
  "code": zod.string().describe('약관 코드'),
  "title": zod.string().describe('약관 제목'),
  "required": zod.boolean().describe('필수 동의 여부'),
  "terminatedAt": zod.iso.datetime({"offset":true}).optional().describe('종료 일시'),
  "status": zod.enum(['DRAFT', 'PUBLISHED', 'TERMINATED']).describe('약관 상태'),
  "organization": zod.string().optional().describe('조직 식별자')
}).describe('문서 기본 정보'),
  "versions": zod.array(zod.object({
  "id": zod.string().describe('약관 버전 식별자'),
  "content": zod.string().describe('약관 내용'),
  "checksum": zod.string().describe('체크섬'),
  "status": zod.enum(['DRAFT', 'PUBLISHED']).describe('버전 상태'),
  "effectiveAt": zod.iso.datetime({"offset":true}).optional().describe('효력 일시'),
  "label": zod.string().describe('버전 라벨')
})).describe('버전 목록'),
  "currentVersion": zod.object({
  "id": zod.string().describe('약관 버전 식별자'),
  "content": zod.string().describe('약관 내용'),
  "checksum": zod.string().describe('체크섬'),
  "status": zod.enum(['DRAFT', 'PUBLISHED']).describe('버전 상태'),
  "effectiveAt": zod.iso.datetime({"offset":true}).optional().describe('효력 일시'),
  "label": zod.string().describe('버전 라벨')
}).nullish().describe('현재 효력 중인 버전')
}).optional()
}))


export const TermsControllerGetTermsDocumentVersionsV1Params = zod.object({
  "id": zod.string()
})

export const termsControllerGetTermsDocumentVersionsV1QueryOffsetDefault = 0;
export const termsControllerGetTermsDocumentVersionsV1QueryLimitDefault = 20;

export const TermsControllerGetTermsDocumentVersionsV1QueryParams = zod.object({
  "sort": zod.array(zod.string()).optional().describe('정렬 필드'),
  "direction": zod.array(zod.enum(['asc', 'desc'])).default([`desc`, `desc`]).describe('정렬 방향'),
  "offset": zod.number().default(termsControllerGetTermsDocumentVersionsV1QueryOffsetDefault).describe('오프셋'),
  "limit": zod.number().default(termsControllerGetTermsDocumentVersionsV1QueryLimitDefault).describe('페이지 크기')
})

export const TermsControllerGetTermsDocumentVersionsV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullish().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.string().describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).optional().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).optional().describe('에러 상세 정보'),
  "message": zod.string().optional().describe('응답 메시지'),
  "traceId": zod.string().optional().describe('추적 ID'),
  "requestId": zod.string().optional().describe('요청 ID')
}).and(zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().describe('약관 버전 식별자'),
  "content": zod.string().describe('약관 내용'),
  "checksum": zod.string().describe('체크섬'),
  "status": zod.enum(['DRAFT', 'PUBLISHED']).describe('버전 상태'),
  "effectiveAt": zod.iso.datetime({"offset":true}).optional().describe('효력 일시'),
  "label": zod.string().describe('버전 라벨')
})).optional()
}))
