/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * AI Base App Platform Service API
 * The AI Base App Platform Service API documentation
 * OpenAPI spec version: 1.0
 */
import * as zod from 'zod';

export const announcementControllerGetAnnouncementPageV1QueryPageDefault = 1;
export const announcementControllerGetAnnouncementPageV1QueryLimitDefault = 20;
export const announcementControllerGetAnnouncementPageV1QueryFiltersIsPublishedDefault = false;

export const AnnouncementControllerGetAnnouncementPageV1QueryParams = zod.object({
  "page": zod.number().default(announcementControllerGetAnnouncementPageV1QueryPageDefault).describe('페이지 번호'),
  "limit": zod.number().default(announcementControllerGetAnnouncementPageV1QueryLimitDefault).describe('페이지 크기'),
  "filters": zod.object({
  "isPublished": zod.boolean().default(announcementControllerGetAnnouncementPageV1QueryFiltersIsPublishedDefault).describe('게시된 공지만 조회할지 여부'),
  "status": zod.enum(['DRAFT', 'SCHEDULED', 'ACTIVE', 'EXPIRED']).optional().describe('게시 상태')
}).optional().describe('필터 조건'),
  "sort": zod.array(zod.enum(['createdAt'])).optional().describe('정렬 필드'),
  "direction": zod.array(zod.enum(['asc', 'desc'])).optional().describe('정렬 방향')
})

export const AnnouncementControllerGetAnnouncementPageV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "page": zod.number().describe('페이지 번호'),
  "totalPages": zod.number().describe('전체 페이지 수'),
  "hasNextPage": zod.boolean().describe('다음 페이지 존재 여부'),
  "hasPrevPage": zod.boolean().describe('이전 페이지 존재 여부'),
  "totalCount": zod.number().describe('전체 개수'),
  "items": zod.array(zod.object({
  "id": zod.string().describe('공지사항 식별자'),
  "title": zod.string().describe('공지사항 제목'),
  "content": zod.string().describe('공지사항 본문 내용'),
  "createdAt": zod.string().describe('생성 일시'),
  "updatedAt": zod.string().describe('수정 일시'),
  "category": zod.enum(['NOTICE', 'MAINTENANCE', 'SECURITY', 'EVENT']).describe('공지 분류'),
  "audience": zod.enum(['ALL', 'PLATFORM', 'ORGANIZATION']).describe('공지 대상'),
  "priority": zod.enum(['LOW', 'NORMAL', 'HIGH']).describe('공지 우선순위'),
  "pinned": zod.boolean().describe('상단 고정 여부'),
  "publishedAt": zod.string().nullable().describe('게시 확정 일시'),
  "startAt": zod.string().nullable().describe('게시 시작일'),
  "endAt": zod.string().nullable().describe('게시 종료일'),
  "status": zod.enum(['DRAFT', 'SCHEDULED', 'ACTIVE', 'EXPIRED']).describe('게시 상태'),
  "isPublished": zod.boolean().describe('게시 확정 여부'),
  "author": zod.string().describe('작성자')
})).describe('공지사항 목록')
}).optional()
}))


export const AnnouncementControllerCreateAnnouncementV1Body = zod.object({
  "title": zod.string().describe('공지사항 제목'),
  "content": zod.string().describe('공지사항 본문'),
  "category": zod.enum(['NOTICE', 'MAINTENANCE', 'SECURITY', 'EVENT']).describe('공지 분류'),
  "audience": zod.enum(['ALL', 'PLATFORM', 'ORGANIZATION']).describe('공지 대상'),
  "priority": zod.enum(['LOW', 'NORMAL', 'HIGH']).describe('공지 우선순위'),
  "pinned": zod.boolean().describe('공지 목록에서 우선 노출할지 여부'),
  "startAt": zod.string().describe('게시 시작일'),
  "endAt": zod.string().describe('게시 종료일'),
  "publishedAt": zod.string().nullable().describe('게시 확정 일시')
})


export const AnnouncementControllerGetAnnouncementV1Params = zod.object({
  "id": zod.string()
})

export const AnnouncementControllerGetAnnouncementV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('공지사항 식별자'),
  "title": zod.string().describe('공지사항 제목'),
  "content": zod.string().describe('공지사항 본문 내용'),
  "createdAt": zod.string().describe('생성 일시'),
  "updatedAt": zod.string().nullable().describe('수정 일시'),
  "category": zod.enum(['NOTICE', 'MAINTENANCE', 'SECURITY', 'EVENT']).describe('공지 분류'),
  "audience": zod.enum(['ALL', 'PLATFORM', 'ORGANIZATION']).describe('공지 대상'),
  "priority": zod.enum(['LOW', 'NORMAL', 'HIGH']).describe('공지 우선순위'),
  "pinned": zod.boolean().describe('상단 고정 여부'),
  "publishedAt": zod.string().nullable().describe('게시 확정 일시'),
  "startAt": zod.string().nullable().describe('게시 시작일'),
  "endAt": zod.string().nullable().describe('게시 종료일'),
  "status": zod.enum(['DRAFT', 'SCHEDULED', 'ACTIVE', 'EXPIRED']).describe('게시 상태'),
  "isPublished": zod.boolean().describe('게시 확정 여부'),
  "author": zod.string().describe('작성자')
}).optional()
}))


export const AnnouncementControllerUpdateAnnouncementV1Params = zod.object({
  "id": zod.string()
})

export const AnnouncementControllerUpdateAnnouncementV1Body = zod.object({
  "id": zod.string().describe('공지사항 식별자'),
  "title": zod.string().optional().describe('공지사항 제목'),
  "content": zod.string().optional().describe('공지사항 본문'),
  "category": zod.enum(['NOTICE', 'MAINTENANCE', 'SECURITY', 'EVENT']).optional().describe('공지 분류'),
  "audience": zod.enum(['ALL', 'PLATFORM', 'ORGANIZATION']).optional().describe('공지 대상'),
  "priority": zod.enum(['LOW', 'NORMAL', 'HIGH']).optional().describe('공지 우선순위'),
  "pinned": zod.boolean().optional().describe('공지 목록에서 우선 노출할지 여부'),
  "startAt": zod.string().optional().describe('게시 시작일'),
  "endAt": zod.string().optional().describe('게시 종료일'),
  "publishedAt": zod.string().nullish().describe('게시 확정 일시')
})

export const AnnouncementControllerUpdateAnnouncementV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('식별자')
}).optional()
}))


export const AnnouncementControllerDeleteAnnouncementV1Params = zod.object({
  "id": zod.string()
})

export const AnnouncementControllerDeleteAnnouncementV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('식별자')
}).optional()
}))


export const AuthControllerGetCsrfTokenV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "csrfToken": zod.string().describe('CSRF 토큰')
}).optional()
}))


export const AuthControllerLoginV1Body = zod.object({
  "email": zod.string().describe('이메일 주소'),
  "password": zod.string().describe('비밀번호')
})


export const AuthControllerMeV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "account": zod.object({
  "id": zod.string().describe('계정 식별자'),
  "email": zod.string().describe('이메일 주소'),
  "status": zod.enum(['ACTIVE', 'INACTIVE']).describe('계정 상태'),
  "lastLoginAt": zod.string().nullable().describe('마지막 로그인 일시'),
  "passwordExpiresAt": zod.string().describe('비밀번호 만료 일시'),
  "isDormant": zod.boolean().describe('휴면 여부'),
  "isPasswordExpired": zod.boolean().describe('비밀번호 만료 여부')
}).describe('계정 정보'),
  "member": zod.object({
  "id": zod.string().describe('멤버 식별자'),
  "name": zod.string().describe('멤버 이름'),
  "status": zod.enum(['ACTIVE', 'INACTIVE']).describe('멤버 상태')
}).describe('멤버 정보'),
  "organization": zod.object({
  "id": zod.string().describe('조직 식별자'),
  "code": zod.string().describe('조직 코드'),
  "name": zod.string().describe('조직 이름'),
  "email": zod.string().describe('조직 이메일'),
  "status": zod.enum(['PENDING', 'ACTIVE', 'INACTIVE', 'REJECTED']).describe('조직 상태')
}).nullable().describe('조직 정보'),
  "permissions": zod.array(zod.string()).describe('권한 목록')
}).optional()
}))


export const AuthControllerGetAllowedResourceListV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('리소스 식별자'),
  "code": zod.string().describe('리소스 코드'),
  "name": zod.string().describe('리소스 이름'),
  "type": zod.enum(['MENU', 'COMPONENT']).describe('리소스 유형'),
  "scope": zod.enum(['PLATFORM', 'ORGANIZATION']).describe('리소스 관리 범위'),
  "path": zod.string().nullable().describe('리소스 경로'),
  "icon": zod.string().nullable().describe('아이콘'),
  "sortOrder": zod.number().nullable().describe('정렬 순서'),
  "actions": zod.array(zod.enum(['CREATE', 'READ', 'UPDATE', 'DELETE'])).describe('리소스 액션 목록'),
  "parent": zod.string().nullable().describe('부모 리소스 식별자'),
  "children": zod.array(zod.unknown()).describe('하위 리소스 목록')
})).describe('권한이 부여된 리소스 목록')
}).optional()
}))


export const AuthControllerGetPendingTermListV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "documentId": zod.string().describe('약관 문서 식별자'),
  "versionId": zod.string().describe('약관 버전 식별자'),
  "organizationId": zod.string().nullable().describe('조직 식별자'),
  "scope": zod.enum(['platform', 'organization']).describe('약관 적용 범위'),
  "version": zod.string().describe('약관 버전 태그'),
  "required": zod.boolean().describe('필수 동의 여부'),
  "title": zod.string().describe('약관 제목'),
  "content": zod.string().describe('약관 내용'),
  "agreed": zod.boolean().describe('동의 여부')
})).describe('동의 대기 약관 목록')
}).optional()
}))


export const AuthControllerAgreeTermsV1Body = zod.object({
  "terms": zod.array(zod.object({
  "termsVersionId": zod.string().describe('약관 버전 식별자'),
  "agreed": zod.boolean().describe('동의 여부')
})).describe('약관 버전별 동의 여부 목록')
})


export const AuthControllerChangePasswordV1Body = zod.object({
  "currentPassword": zod.string().describe('현재 비밀번호'),
  "newPassword": zod.string().describe('새 비밀번호'),
  "confirmPassword": zod.string().describe('새 비밀번호 확인')
})


export const I18nControllerGetLocaleListV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "code": zod.string().describe('로케일 코드'),
  "name": zod.string().describe('로케일 이름'),
  "regionCode": zod.string().nullable().describe('지역 코드'),
  "direction": zod.enum(['ltr', 'rtl']).describe('문자 방향'),
  "isActive": zod.boolean().describe('활성화 여부'),
  "sortOrder": zod.number().nullable().describe('정렬 순서')
})).describe('활성 로케일 목록')
}).optional()
}))


export const JoinControllerVerifyV1QueryParams = zod.object({
  "token": zod.string().describe('초대 토큰')
})

export const JoinControllerVerifyV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "inviteId": zod.string().describe('초대 식별자'),
  "email": zod.string().describe('초대 이메일'),
  "name": zod.string().describe('초대 대상 이름'),
  "organizationId": zod.string().describe('조직 식별자'),
  "organizationName": zod.string().describe('조직 이름'),
  "roleId": zod.string().describe('역할 식별자'),
  "roleName": zod.string().describe('역할 이름'),
  "status": zod.enum(['QUEUED', 'PENDING', 'EXPIRED', 'CANCELED', 'ACCEPTED', 'REJECTED']).describe('초대 상태'),
  "expiredAt": zod.string().nullable().describe('초대 만료 시각'),
  "terms": zod.array(zod.object({
  "documentId": zod.string().describe('약관 문서 식별자'),
  "versionId": zod.string().describe('약관 버전 식별자'),
  "organizationId": zod.string().nullable().describe('조직 식별자'),
  "scope": zod.enum(['platform', 'organization']).describe('약관 적용 범위'),
  "required": zod.boolean().describe('필수 동의 여부'),
  "title": zod.string().describe('약관 제목'),
  "version": zod.string().describe('약관 버전 태그'),
  "content": zod.string().describe('약관 내용')
})).describe('가입 시 동의해야 하는 약관 목록')
}).optional()
}))


export const JoinControllerAcceptV1Body = zod.object({
  "token": zod.string().describe('초대 토큰'),
  "profile": zod.object({
  "name": zod.string().describe('가입자 이름'),
  "email": zod.string().describe('가입 이메일'),
  "password": zod.string().describe('비밀번호')
}).describe('가입정보'),
  "terms": zod.array(zod.object({
  "termsVersionId": zod.string().describe('약관 버전 식별자'),
  "agreed": zod.boolean().describe('동의 여부')
})).describe('약관 동의 목록')
})


export const MembersControllerCreateInviteV1Body = zod.object({
  "name": zod.string().describe('초대할 사람 이름'),
  "email": zod.string().describe('초대할 사람 이메일'),
  "role": zod.string().describe('부여할 역할'),
  "note": zod.string().nullable().describe('메모\/메모사항')
})


export const membersControllerGetInvitePageV1QueryPageDefault = 1;
export const membersControllerGetInvitePageV1QueryLimitDefault = 20;

export const MembersControllerGetInvitePageV1QueryParams = zod.object({
  "page": zod.number().default(membersControllerGetInvitePageV1QueryPageDefault).describe('페이지 번호'),
  "limit": zod.number().default(membersControllerGetInvitePageV1QueryLimitDefault).describe('페이지 크기'),
  "filters": zod.object({
  "search": zod.string().optional().describe('검색어')
}).optional().describe('필터 조건'),
  "sort": zod.array(zod.enum(['createdAt'])).optional().describe('정렬 필드'),
  "direction": zod.array(zod.enum(['asc', 'desc'])).optional().describe('정렬 방향')
})

export const MembersControllerGetInvitePageV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "page": zod.number().describe('페이지 번호'),
  "totalPages": zod.number().describe('전체 페이지 수'),
  "hasNextPage": zod.boolean().describe('다음 페이지 존재 여부'),
  "hasPrevPage": zod.boolean().describe('이전 페이지 존재 여부'),
  "totalCount": zod.number().describe('전체 개수'),
  "items": zod.array(zod.object({
  "id": zod.string().describe('초대 식별자'),
  "name": zod.string().describe('초대 대상 이름'),
  "email": zod.string().describe('초대 대상 이메일'),
  "status": zod.enum(['QUEUED', 'PENDING', 'EXPIRED', 'CANCELED', 'ACCEPTED', 'REJECTED']).describe('초대 상태'),
  "roleId": zod.string().describe('권한 식별자'),
  "roleCode": zod.string().describe('권한 코드'),
  "roleName": zod.string().describe('권한 이름'),
  "note": zod.string().nullable().describe('초대 메모'),
  "createdAt": zod.string().describe('생성 일시')
})).describe('초대 이력 목록')
}).optional()
}))


export const MembersControllerCancelInviteV1Params = zod.object({
  "id": zod.string()
})


export const MembersControllerResendInviteV1Params = zod.object({
  "id": zod.string()
})


export const MembersControllerUpdateMemberStatusV1Body = zod.object({
  "id": zod.string().describe('멤버 식별자'),
  "status": zod.enum(['ACTIVE', 'INACTIVE']).optional().describe('변경할 상태')
})


export const MembersControllerUpdateMemberRoleV1Body = zod.object({
  "id": zod.string().describe('멤버 식별자'),
  "role": zod.string().optional().describe('변경할 역할')
})


export const membersControllerGetMemberPageV1QueryPageDefault = 1;
export const membersControllerGetMemberPageV1QueryLimitDefault = 20;

export const MembersControllerGetMemberPageV1QueryParams = zod.object({
  "page": zod.number().default(membersControllerGetMemberPageV1QueryPageDefault).describe('페이지 번호'),
  "limit": zod.number().default(membersControllerGetMemberPageV1QueryLimitDefault).describe('페이지 크기'),
  "filters": zod.object({
  "status": zod.enum(['ACTIVE', 'INACTIVE']).optional().describe('멤버 상태 필터'),
  "search": zod.string().optional().describe('검색어')
}).optional().describe('필터 조건'),
  "sort": zod.array(zod.enum(['createdAt', 'name', 'status', 'lastLoginAt'])).optional().describe('정렬 필드'),
  "direction": zod.array(zod.enum(['asc', 'desc'])).optional().describe('정렬 방향')
})

export const MembersControllerGetMemberPageV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "page": zod.number().describe('페이지 번호'),
  "totalPages": zod.number().describe('전체 페이지 수'),
  "hasNextPage": zod.boolean().describe('다음 페이지 존재 여부'),
  "hasPrevPage": zod.boolean().describe('이전 페이지 존재 여부'),
  "totalCount": zod.number().describe('전체 개수'),
  "items": zod.array(zod.object({
  "id": zod.string().describe('멤버 식별자'),
  "name": zod.string().describe('멤버 이름'),
  "email": zod.string().describe('이메일'),
  "status": zod.enum(['ACTIVE', 'INACTIVE']).describe('멤버 상태'),
  "roles": zod.array(zod.string()).nullable().describe('권한 목록'),
  "lastLoginAt": zod.string().nullable().describe('최근 로그인'),
  "createdAt": zod.string().describe('생성 일시')
})).describe('멤버 목록')
}).optional()
}))


export const MembersControllerGetMemberV1Params = zod.object({
  "id": zod.string()
})

export const MembersControllerGetMemberV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('멤버 식별자'),
  "name": zod.string().describe('멤버 이름'),
  "email": zod.string().describe('이메일'),
  "status": zod.enum(['ACTIVE', 'INACTIVE']).describe('멤버 상태'),
  "roles": zod.array(zod.string()).nullable().describe('권한 목록'),
  "lastLoginAt": zod.string().nullable().describe('최근 로그인'),
  "createdAt": zod.string().describe('생성 일시')
}).optional()
}))


export const OrganizationControllerGetOrganizationListV1QueryParams = zod.object({
  "offset": zod.number().optional().describe('오프셋'),
  "limit": zod.number().nullish().describe('페이지 크기'),
  "filters": zod.object({
  "status": zod.enum(['PENDING', 'ACTIVE', 'INACTIVE', 'REJECTED']).optional().describe('메타데이터 날짜로 유추되는 조직 상태 필터')
}).optional().describe('필터 조건'),
  "sort": zod.array(zod.enum(['createdAt'])).optional().describe('정렬 필드'),
  "direction": zod.array(zod.enum(['asc', 'desc'])).optional().describe('정렬 방향')
})

export const OrganizationControllerGetOrganizationListV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('조직 식별자'),
  "name": zod.string().describe('조직 이름'),
  "createdAt": zod.string().describe('생성 일시'),
  "code": zod.string().describe('조직 코드'),
  "status": zod.enum(['PENDING', 'ACTIVE', 'INACTIVE', 'REJECTED']).describe('조직 상태')
})).describe('조직 목록')
}).optional()
}))


export const OrganizationControllerUpdateOrganizationV1Body = zod.object({
  "name": zod.string().optional().describe('조직 이름'),
  "email": zod.string().optional().describe('대표 이메일')
})

export const OrganizationControllerUpdateOrganizationV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('식별자')
}).optional()
}))


export const OrganizationControllerGetOrganizationRoleListV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('조직 역할 식별자'),
  "code": zod.string().describe('조직 역할 코드'),
  "name": zod.string().describe('조직 역할 이름'),
  "description": zod.string().nullable().describe('조직 역할 설명'),
  "sortOrder": zod.number().nullable().describe('조직 역할 정렬 순서')
})).describe('조직 역할 목록')
}).optional()
}))


export const OrganizationControllerCreateOrganizationRoleV1Body = zod.object({
  "code": zod.string().describe('조직 역할 코드'),
  "name": zod.string().describe('조직 역할 이름'),
  "description": zod.string().describe('조직 역할 설명'),
  "sortOrder": zod.number().nullable().describe('조직 역할 정렬 순서')
})


export const OrganizationControllerUpdateOrganizationRoleV1Params = zod.object({
  "id": zod.string()
})

export const OrganizationControllerUpdateOrganizationRoleV1Body = zod.object({
  "id": zod.string().describe('조직 역할 식별자'),
  "code": zod.string().optional().describe('조직 역할 코드'),
  "name": zod.string().optional().describe('조직 역할 이름'),
  "description": zod.string().optional().describe('조직 역할 설명')
})

export const OrganizationControllerUpdateOrganizationRoleV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('식별자')
}).optional()
}))


export const OrganizationControllerDeleteOrganizationRoleV1Params = zod.object({
  "id": zod.string()
})

export const OrganizationControllerDeleteOrganizationRoleV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('식별자')
}).optional()
}))


export const OrganizationControllerUpdateOrganizationRoleSortV1Body = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('조직 역할 식별자'),
  "sortOrder": zod.number().describe('정렬 순서')
})).describe('정렬 대상 목록')
})


export const OrganizationControllerApproveOrganizationV1Params = zod.object({
  "id": zod.string()
})

export const OrganizationControllerApproveOrganizationV1Body = zod.object({
  "id": zod.string().describe('조직 식별자'),
  "approve": zod.boolean().describe('승인 여부')
})

export const OrganizationControllerApproveOrganizationV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('식별자')
}).optional()
}))


export const SignupControllerGetSignupTermListV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "documentId": zod.string().describe('약관 문서 식별자'),
  "versionId": zod.string().describe('약관 버전 식별자'),
  "organizationId": zod.string().nullable().describe('조직 식별자'),
  "scope": zod.enum(['platform', 'organization']).describe('약관 적용 범위'),
  "version": zod.string().describe('약관 버전 태그'),
  "required": zod.boolean().describe('필수 동의 여부'),
  "title": zod.string().describe('약관 제목'),
  "content": zod.string().describe('약관 내용')
})).describe('회원가입용 플랫폼 약관 목록')
}).optional()
}))


export const ResourceControllerCreateResourceV1Body = zod.object({
  "code": zod.string().describe('리소스 코드'),
  "name": zod.string().describe('리소스 이름'),
  "type": zod.enum(['MENU', 'COMPONENT']).describe('리소스 유형'),
  "scope": zod.enum(['PLATFORM', 'ORGANIZATION']).describe('리소스 관리 범위'),
  "parent": zod.string().nullable().describe('부모 리소스 식별자'),
  "path": zod.string().nullable().describe('리소스 경로'),
  "icon": zod.string().nullable().describe('아이콘'),
  "sortOrder": zod.number().nullable().describe('정렬 순서'),
  "actions": zod.array(zod.enum(['CREATE', 'READ', 'UPDATE', 'DELETE'])).describe('리소스 액션 목록')
})


export const ResourceControllerUpdateResourceV1Body = zod.object({
  "id": zod.string().describe('리소스 식별자'),
  "code": zod.string().optional().describe('리소스 코드'),
  "name": zod.string().optional().describe('리소스 이름'),
  "type": zod.enum(['MENU', 'COMPONENT']).optional().describe('리소스 유형'),
  "scope": zod.enum(['PLATFORM', 'ORGANIZATION']).optional().describe('리소스 관리 범위'),
  "parent": zod.string().nullish().describe('부모 리소스 식별자'),
  "path": zod.string().nullish().describe('리소스 경로'),
  "icon": zod.string().nullish().describe('아이콘'),
  "sortOrder": zod.number().nullish().describe('정렬 순서'),
  "actions": zod.array(zod.enum(['CREATE', 'READ', 'UPDATE', 'DELETE'])).optional().describe('리소스 액션 목록')
})


export const ResourceControllerDeleteResourceV1Body = zod.object({
  "id": zod.string().describe('리소스 식별자')
})


export const ResourceControllerUpdateResourceSortV1Body = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('리소스 식별자'),
  "sortOrder": zod.number().describe('정렬 순서'),
  "parent": zod.string().nullable().describe('부모 리소스 식별자')
})).describe('정렬 대상 목록')
})


export const ResourceControllerUpdatePermissionSetPermissionsV1Body = zod.object({
  "id": zod.string().describe('권한 세트 식별자'),
  "permissionCodes": zod.array(zod.string()).optional().describe('권한 코드 목록')
})


export const ResourceControllerGetRolePermissionListV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('역할 권한 식별자'),
  "code": zod.string().describe('역할 코드'),
  "name": zod.string().describe('역할 권한 이름'),
  "description": zod.string().nullable().describe('역할 권한 설명'),
  "permissions": zod.array(zod.string()).describe('권한 코드 목록')
})).describe('역할 권한 목록')
}).optional()
}))


export const ResourceControllerGetPermissionMapV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('리소스 식별자'),
  "code": zod.string().describe('리소스 코드'),
  "name": zod.string().describe('리소스 이름'),
  "type": zod.enum(['MENU', 'COMPONENT']).describe('리소스 유형'),
  "scope": zod.enum(['PLATFORM', 'ORGANIZATION']).describe('리소스 관리 범위'),
  "path": zod.string().nullable().describe('리소스 경로'),
  "icon": zod.string().nullable().describe('아이콘'),
  "sortOrder": zod.number().nullable().describe('정렬 순서'),
  "actions": zod.array(zod.enum(['CREATE', 'READ', 'UPDATE', 'DELETE'])).describe('리소스 액션 목록'),
  "parent": zod.string().nullable().describe('부모 리소스 식별자'),
  "children": zod.array(zod.unknown()).describe('하위 리소스 목록')
})).describe('리소스 목록')
}).optional()
}))


export const ResourceControllerGetResourceV1Params = zod.object({
  "id": zod.string()
})

export const ResourceControllerGetResourceV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('리소스 식별자'),
  "code": zod.string().describe('리소스 코드'),
  "name": zod.string().describe('리소스 이름'),
  "type": zod.enum(['MENU', 'COMPONENT']).describe('리소스 유형'),
  "scope": zod.enum(['PLATFORM', 'ORGANIZATION']).describe('리소스 관리 범위'),
  "path": zod.string().nullable().describe('리소스 경로'),
  "icon": zod.string().nullable().describe('아이콘'),
  "sortOrder": zod.number().nullable().describe('정렬 순서'),
  "actions": zod.array(zod.enum(['CREATE', 'READ', 'UPDATE', 'DELETE'])).describe('리소스 액션 목록'),
  "parent": zod.string().nullable().describe('부모 리소스 식별자')
}).optional()
}))


export const ResourceControllerGetResourceListV1QueryParams = zod.object({
  "offset": zod.number().optional().describe('오프셋'),
  "limit": zod.number().nullish().describe('페이지 크기'),
  "filters": zod.object({
  "scope": zod.enum(['PLATFORM', 'ORGANIZATION']).optional().describe('리소스 관리 범위')
}).optional().describe('필터 조건'),
  "sort": zod.array(zod.enum(['sortOrder', 'code'])).optional().describe('정렬 필드'),
  "direction": zod.array(zod.enum(['asc', 'desc'])).optional().describe('정렬 방향')
})

export const ResourceControllerGetResourceListV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('리소스 식별자'),
  "code": zod.string().describe('리소스 코드'),
  "name": zod.string().describe('리소스 이름'),
  "type": zod.enum(['MENU', 'COMPONENT']).describe('리소스 유형'),
  "scope": zod.enum(['PLATFORM', 'ORGANIZATION']).describe('리소스 관리 범위'),
  "path": zod.string().nullable().describe('리소스 경로'),
  "icon": zod.string().nullable().describe('아이콘'),
  "sortOrder": zod.number().nullable().describe('정렬 순서'),
  "actions": zod.array(zod.enum(['CREATE', 'READ', 'UPDATE', 'DELETE'])).describe('리소스 액션 목록'),
  "parent": zod.string().nullable().describe('부모 리소스 식별자'),
  "children": zod.array(zod.unknown()).describe('하위 리소스 목록')
})).describe('리소스 목록')
}).optional()
}))


export const supportControllerGetTicketPageV1QueryPageDefault = 1;
export const supportControllerGetTicketPageV1QueryLimitDefault = 20;

export const SupportControllerGetTicketPageV1QueryParams = zod.object({
  "page": zod.number().default(supportControllerGetTicketPageV1QueryPageDefault).describe('페이지 번호'),
  "limit": zod.number().default(supportControllerGetTicketPageV1QueryLimitDefault).describe('페이지 크기'),
  "filters": zod.object({
  "organizationId": zod.string().optional().describe('조직 필터'),
  "status": zod.enum(['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED']).optional().describe('티켓 상태 필터')
}).optional().describe('필터 조건'),
  "sort": zod.array(zod.enum(['createdAt'])).optional().describe('정렬 필드'),
  "direction": zod.array(zod.enum(['asc', 'desc'])).optional().describe('정렬 방향')
})

export const SupportControllerGetTicketPageV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "page": zod.number().describe('페이지 번호'),
  "totalPages": zod.number().describe('전체 페이지 수'),
  "hasNextPage": zod.boolean().describe('다음 페이지 존재 여부'),
  "hasPrevPage": zod.boolean().describe('이전 페이지 존재 여부'),
  "totalCount": zod.number().describe('전체 개수'),
  "items": zod.array(zod.object({
  "id": zod.string().describe('티켓 식별자'),
  "title": zod.string().describe('티켓 제목'),
  "content": zod.string().describe('티켓 내용'),
  "status": zod.enum(['OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED']).describe('티켓 상태'),
  "priority": zod.enum(['LOW', 'MEDIUM', 'HIGH', 'URGENT']).describe('티켓 우선순위'),
  "createdAt": zod.string().describe('생성 일시'),
  "organizationId": zod.string().describe('조직 식별자')
})).describe('티켓 목록')
}).optional()
}))


export const TermsControllerGetTermsDocumentListV1QueryParams = zod.object({
  "offset": zod.number().optional().describe('오프셋'),
  "limit": zod.number().nullish().describe('페이지 크기'),
  "filters": zod.object({
  "scope": zod.enum(['platform', 'organization']).optional().describe('조회 scope'),
  "status": zod.enum(['DRAFT', 'PUBLISHED', 'TERMINATED']).optional().describe('약관 상태 필터')
}).optional().describe('필터 조건'),
  "sort": zod.array(zod.enum(['createdAt'])).optional().describe('정렬 필드'),
  "direction": zod.array(zod.enum(['asc', 'desc'])).optional().describe('정렬 방향')
})

export const TermsControllerGetTermsDocumentListV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('약관 문서 식별자'),
  "code": zod.string().describe('약관 코드'),
  "title": zod.string().describe('약관 제목'),
  "required": zod.boolean().describe('필수 동의 여부'),
  "terminatedAt": zod.string().nullable().describe('종료 일시'),
  "status": zod.enum(['DRAFT', 'PUBLISHED', 'TERMINATED']).describe('약관 상태'),
  "organizationId": zod.string().nullable().describe('조직 식별자')
})).describe('약관 문서 목록')
}).optional()
}))


export const TermsControllerCreateTermsDocumentV1Body = zod.object({
  "code": zod.string().describe('약관 코드'),
  "title": zod.string().describe('약관 제목'),
  "required": zod.boolean().describe('필수 동의 여부'),
  "scope": zod.enum(['platform', 'organization']).describe('적용 범위')
})


export const TermsControllerGetTermsDocumentV1Params = zod.object({
  "id": zod.string()
})

export const TermsControllerGetTermsDocumentV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "document": zod.object({
  "id": zod.string().describe('약관 문서 식별자'),
  "code": zod.string().describe('약관 코드'),
  "title": zod.string().describe('약관 제목'),
  "required": zod.boolean().describe('필수 동의 여부'),
  "terminatedAt": zod.string().nullable().describe('종료 일시'),
  "status": zod.enum(['DRAFT', 'PUBLISHED', 'TERMINATED']).describe('약관 상태'),
  "organizationId": zod.string().nullable().describe('조직 식별자')
}).describe('문서 기본 정보'),
  "versions": zod.array(zod.object({
  "id": zod.string().describe('약관 버전 식별자'),
  "content": zod.string().describe('약관 내용'),
  "checksum": zod.string().describe('체크섬'),
  "status": zod.enum(['DRAFT', 'PUBLISHED']).describe('버전 상태'),
  "effectiveAt": zod.string().describe('효력 일시'),
  "label": zod.string().describe('버전 라벨'),
  "summary": zod.string().nullable().describe('개정 요약'),
  "reason": zod.string().nullable().describe('변경 사유')
})).describe('버전 목록'),
  "currentVersion": zod.object({
  "id": zod.string().describe('약관 버전 식별자'),
  "content": zod.string().describe('약관 내용'),
  "checksum": zod.string().describe('체크섬'),
  "status": zod.enum(['DRAFT', 'PUBLISHED']).describe('버전 상태'),
  "effectiveAt": zod.string().describe('효력 일시'),
  "label": zod.string().describe('버전 라벨'),
  "summary": zod.string().nullable().describe('개정 요약'),
  "reason": zod.string().nullable().describe('변경 사유')
}).nullable().describe('현재 효력 중인 버전')
}).optional()
}))


export const TermsControllerGetTermsDocumentVersionsV1Params = zod.object({
  "id": zod.string()
})

export const TermsControllerGetTermsDocumentVersionsV1QueryParams = zod.object({
  "offset": zod.number().optional().describe('오프셋'),
  "limit": zod.number().nullish().describe('페이지 크기'),
  "filters": zod.looseObject({

}).optional().describe('필터 조건'),
  "sort": zod.array(zod.enum(['effectiveAt', 'createdAt'])).optional().describe('정렬 필드'),
  "direction": zod.array(zod.enum(['asc', 'desc'])).optional().describe('정렬 방향')
})

export const TermsControllerGetTermsDocumentVersionsV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "items": zod.array(zod.object({
  "id": zod.string().describe('약관 버전 식별자'),
  "content": zod.string().describe('약관 내용'),
  "checksum": zod.string().describe('체크섬'),
  "status": zod.enum(['DRAFT', 'PUBLISHED']).describe('버전 상태'),
  "effectiveAt": zod.string().describe('효력 일시'),
  "label": zod.string().describe('버전 라벨'),
  "summary": zod.string().nullable().describe('개정 요약'),
  "reason": zod.string().nullable().describe('변경 사유')
})).describe('약관 버전 목록')
}).optional()
}))


export const TermsControllerCreateTermsDocumentVersionV1Params = zod.object({
  "documentId": zod.string()
})

export const TermsControllerCreateTermsDocumentVersionV1Body = zod.object({
  "label": zod.string().describe('버전 라벨'),
  "effectiveAt": zod.string().describe('효력 일시'),
  "status": zod.enum(['DRAFT', 'PUBLISHED']).describe('버전 상태'),
  "content": zod.string().describe('약관 본문'),
  "summary": zod.string().describe('개정 요약'),
  "reason": zod.string().describe('변경 사유')
})


export const TermsControllerDeleteTermsDocumentV1Params = zod.object({
  "documentId": zod.string()
})

export const TermsControllerDeleteTermsDocumentV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('식별자')
}).optional()
}))


export const TermsControllerScheduleTermsDocumentTerminationV1Params = zod.object({
  "documentId": zod.string()
})

export const TermsControllerScheduleTermsDocumentTerminationV1Body = zod.object({
  "terminatedAt": zod.string().describe('종료 일시')
})

export const TermsControllerScheduleTermsDocumentTerminationV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('식별자')
}).optional()
}))


export const TermsControllerCancelTermsDocumentTerminationV1Params = zod.object({
  "documentId": zod.string()
})

export const TermsControllerCancelTermsDocumentTerminationV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('식별자')
}).optional()
}))


export const TermsControllerDeleteTermsDocumentVersionV1Params = zod.object({
  "documentId": zod.string(),
  "versionId": zod.string()
})

export const TermsControllerDeleteTermsDocumentVersionV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('식별자')
}).optional()
}))


export const TermsControllerUpdateTermsDocumentVersionV1Params = zod.object({
  "documentId": zod.string(),
  "versionId": zod.string()
})

export const TermsControllerUpdateTermsDocumentVersionV1Body = zod.object({
  "id": zod.string().describe('리소스 식별자'),
  "label": zod.string().optional().describe('버전 라벨'),
  "effectiveAt": zod.string().optional().describe('효력 일시'),
  "status": zod.enum(['DRAFT', 'PUBLISHED']).optional().describe('버전 상태'),
  "content": zod.string().optional().describe('약관 본문'),
  "summary": zod.string().optional().describe('개정 요약'),
  "reason": zod.string().optional().describe('변경 사유')
})

export const TermsControllerUpdateTermsDocumentVersionV1Response = zod.object({
  "success": zod.boolean().describe('성공 여부'),
  "data": zod.looseObject({

}).nullable().describe('응답 데이터'),
  "error": zod.object({
  "code": zod.enum(['INTERNAL_ERROR', 'INACTIVE_ACCOUNT', 'INACTIVE_MEMBER', 'INACTIVE_ORGANIZATION', 'DORMANT_ACCOUNT', 'PASSWORD_CHANGE_REQUIRED', 'TERMS_AGREEMENT_REQUIRED', 'INSUFFICIENT_PERMISSIONS', 'ANNOUNCEMENT_NOT_FOUND', 'REQUEST_CONTEXT_NOT_FOUND', 'MEMBER_MISMATCH', 'TERMS_VERSION_NOT_AVAILABLE', 'TERMS_VERSION_NOT_FOUND', 'ACCOUNT_NOT_FOUND', 'ACCOUNT_LOCKED', 'INVALID_CURRENT_PASSWORD', 'INVALID_CREDENTIALS', 'INVITE_NOT_FOUND', 'INVITE_MAIL_DELIVERY_NOT_READY', 'MAIL_SEND_FAILED', 'ORGANIZATION_NOT_FOUND', 'INVITER_NOT_FOUND', 'ROLE_NOT_FOUND', 'LOAD_FAILED', 'MEMBER_NOT_FOUND', 'CANNOT_MODIFY_SELF', 'LAST_OWNER_ROLE_CANNOT_BE_CHANGED', 'LAST_OWNER_STATUS_CANNOT_BE_CHANGED', 'RESOURCE_NOT_FOUND', 'DOCUMENT_NOT_FOUND', 'TERMINATED_DOCUMENT_CANNOT_CREATE_VERSION', 'TERMINATED_DOCUMENT_CANNOT_UPDATE_VERSION']).describe('에러 코드'),
  "message": zod.union([zod.string(),zod.array(zod.string())]).describe('에러 메시지'),
  "details": zod.looseObject({

}).nullable().describe('상세 정보'),
  "status": zod.number().describe('HTTP 상태 코드')
}).nullable().describe('에러 상세 정보'),
  "message": zod.string().nullable().describe('응답 메시지'),
  "traceId": zod.string().nullable().describe('추적 ID'),
  "requestId": zod.string().nullable().describe('요청 ID')
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().describe('식별자')
}).optional()
}))
