apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-service-gateway-to-redis
  namespace: dev-web
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: service-gateway
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: dev-infra
    ports:
    - protocol: TCP
      port: 6379
