apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-redis-from-apps
  namespace: dev-infra
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: dev-api
      podSelector:
        matchLabels:
          app.kubernetes.io/name: platform-auth-service
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: dev-web
      podSelector:
        matchLabels:
          app.kubernetes.io/name: platform-gateway
    ports:
    - protocol: TCP
      port: 6379
